// Maps normalized skill keywords → important subtopics to learn
export const SKILL_TOPICS: Record<string, string[]> = {
  html: [
    "Semantic Elements — header, footer, article, section, nav, aside, main",
    "Forms & Input Types — text, email, password, select, checkbox, radio, file",
    "Tables — thead, tbody, tfoot, colspan, rowspan",
    "Media Elements — img, video, audio, figure, figcaption",
    "Head & Metadata — meta tags, Open Graph, favicon, viewport",
    "Accessibility — ARIA roles, alt text, label, tabindex, skip links",
    "HTML5 APIs — Geolocation, Canvas, Web Storage, Drag & Drop",
  ],
  css: [
    "Box Model — margin, padding, border, box-sizing",
    "Flexbox — flex-direction, justify-content, align-items, flex-wrap",
    "CSS Grid — grid-template-columns, grid-area, gap",
    "Selectors & Specificity — class, id, attribute, combinators",
    "Responsive Design — media queries, mobile-first, breakpoints",
    "Animations & Transitions — keyframes, transition, transform",
    "CSS Variables — var(), :root, custom properties",
    "Pseudo-classes & Elements — :hover, :focus, ::before, ::after",
    "Typography — font-family, line-height, letter-spacing, web fonts",
    "Dark Mode — prefers-color-scheme, color-scheme",
  ],
  javascript: [
    "Variables & Data Types — var, let, const, primitives, type coercion",
    "Functions — declarations, expressions, arrow functions, closures",
    "Arrays & Methods — map, filter, reduce, find, forEach, spread",
    "Objects & Destructuring — spread, rest, optional chaining",
    "DOM Manipulation — querySelector, createElement, classList, innerHTML",
    "Events — addEventListener, event delegation, bubbling & capturing",
    "Promises & Async/Await — then/catch, async functions, error handling",
    "ES6+ Features — template literals, destructuring, modules, generators",
    "Error Handling — try/catch/finally, custom errors",
    "Fetch API — GET, POST, headers, JSON, async patterns",
    "Browser APIs — localStorage, sessionStorage, History, Clipboard",
  ],
  typescript: [
    "Type Annotations — primitives, arrays, tuples, enums",
    "Interfaces & Types — type aliases, interface merging",
    "Union & Intersection Types",
    "Generics — generic functions, generic interfaces, constraints",
    "Type Guards — typeof, instanceof, in, discriminated unions",
    "Utility Types — Partial, Readonly, Pick, Omit, Record, Exclude",
    "Enums — const enums, numeric vs string enums",
    "Modules & Namespaces",
    "Strict Mode & tsconfig.json configuration",
    "Declaration Files (.d.ts)",
  ],
  react: [
    "JSX Syntax & Expressions",
    "Components — function components, composition, naming",
    "Props & PropTypes — passing data, default props, children",
    "State — useState, lifting state up, derived state",
    "useEffect — dependencies, cleanup, data fetching",
    "Event Handling — onClick, onChange, form submission",
    "Lists & Keys — mapping arrays, stable keys",
    "Conditional Rendering — ternary, && operator, early return",
    "React Router — Route, Link, useNavigate, useParams",
    "Context API — createContext, useContext, Provider",
    "Custom Hooks — extraction, reuse, naming conventions",
    "Performance — useMemo, useCallback, React.memo",
    "Error Boundaries & Suspense",
  ],
  "node.js": [
    "Modules — require, import/export, CommonJS vs ESM",
    "npm & Package.json — scripts, dependencies, devDependencies",
    "HTTP Module — createServer, request, response",
    "File System — fs.readFile, fs.writeFile, streams",
    "Environment Variables — .env, process.env, dotenv",
    "Express.js Basics — routing, app.get/post, res.json",
    "Middleware — express.json, cors, custom middleware",
    "REST API Design — HTTP methods, status codes, JSON",
    "Authentication — JWT, bcrypt, cookie-parser",
    "Database Integration — Prisma, Mongoose, pg",
    "Error Handling Middleware",
  ],
  node: [
    "Modules — require, import/export, CommonJS vs ESM",
    "npm & Package.json — scripts, dependencies, devDependencies",
    "HTTP Module — createServer, request, response",
    "File System — fs.readFile, fs.writeFile, streams",
    "Environment Variables — .env, process.env, dotenv",
    "Express.js Basics — routing, app.get/post, res.json",
    "Middleware — express.json, cors, custom middleware",
    "REST API Design — HTTP methods, status codes, JSON",
    "Authentication — JWT, bcrypt, cookie-parser",
    "Database Integration — Prisma, Mongoose, pg",
    "Error Handling Middleware",
  ],
  sql: [
    "SELECT — basic queries, WHERE, LIMIT, ORDER BY",
    "Aggregate Functions — COUNT, SUM, AVG, MIN, MAX with GROUP BY",
    "JOINs — INNER, LEFT, RIGHT, FULL OUTER JOIN",
    "Subqueries & CTEs (Common Table Expressions)",
    "INSERT, UPDATE, DELETE",
    "Indexes — B-tree, unique, composite, when to use",
    "Transactions — COMMIT, ROLLBACK, SAVEPOINT, ACID",
    "Views & Stored Procedures",
    "Normalization — 1NF, 2NF, 3NF, BCNF",
    "SQL Functions — string, date, numeric",
  ],
  git: [
    "Core Commands — init, clone, add, commit, status, log",
    "Branching — branch, checkout, switch, merge",
    "Remote — push, pull, fetch, remote add",
    "Resolving Merge Conflicts",
    "Rebase — interactive rebase, rebase vs merge",
    ".gitignore — patterns, global ignore",
    "Stashing — git stash, pop, list",
    "Tags & Releases",
    "Git Hooks — pre-commit, commit-msg",
    "Git Flow Workflow",
  ],
  python: [
    "Variables & Data Types — int, float, str, bool, None",
    "Functions — def, lambda, *args, **kwargs, default params",
    "Collections — list, tuple, dict, set and their methods",
    "Control Flow — if/elif/else, for/while, list comprehensions",
    "File I/O — open(), read, write, with statement",
    "Classes & OOP — class, __init__, inheritance, dunder methods",
    "Modules & Packages — import, from, pip, virtual environments",
    "Decorators & Generators",
    "Exception Handling — try/except/finally, custom exceptions",
    "Standard Library — os, sys, datetime, json, itertools",
  ],
  docker: [
    "Containers vs VMs — benefits and trade-offs",
    "Dockerfile — FROM, RUN, COPY, EXPOSE, CMD, ENTRYPOINT",
    "Images — build, tag, push, pull, layers",
    "Containers — run, stop, rm, exec, logs, inspect",
    "Docker Compose — services, volumes, networks, depends_on",
    "Volumes & Bind Mounts — data persistence",
    "Networks — bridge, host, overlay",
    "Docker Hub & Private Registries",
    "Multi-stage Builds — reducing image size",
    "Environment Variables in Docker",
  ],
  kubernetes: [
    "Architecture — control plane, nodes, kubelet, etcd",
    "Pods — single vs multi-container, lifecycle",
    "Deployments & ReplicaSets — rolling updates, rollbacks",
    "Services — ClusterIP, NodePort, LoadBalancer, Ingress",
    "ConfigMaps & Secrets",
    "Persistent Volumes & Persistent Volume Claims",
    "Namespaces — isolation, resource quotas",
    "Helm Charts — templating, releases, values.yaml",
    "Horizontal Pod Autoscaler",
    "kubectl — common commands and debugging",
  ],
  aws: [
    "IAM — Users, Groups, Roles, Policies, MFA",
    "EC2 — instances, AMIs, security groups, key pairs",
    "S3 — buckets, objects, permissions, versioning, lifecycle",
    "RDS — managed databases, Multi-AZ, read replicas",
    "Lambda — serverless functions, triggers, layers",
    "CloudFront — CDN, distributions, cache behaviors",
    "VPC — subnets, route tables, NAT gateway, VPN",
    "Route 53 — hosted zones, record types, routing policies",
    "CloudWatch — metrics, alarms, logs",
    "AWS CLI & SDK usage",
  ],
  mongodb: [
    "Collections & Documents — BSON, _id, schema-less design",
    "CRUD — insertOne, find, updateOne, deleteOne, operators",
    "Query Operators — comparison, logical, element, array",
    "Indexes — single field, compound, text, TTL",
    "Aggregation Pipeline — $match, $group, $project, $lookup",
    "Schema Design — embedding vs referencing",
    "Mongoose ODM — schemas, models, validation, middleware",
    "Transactions & Sessions",
    "Atlas & Connection String",
    "Performance & Explain Plans",
  ],
  graphql: [
    "Schema Definition Language — types, fields, scalars",
    "Queries — basic queries, nested fields, aliases, fragments",
    "Mutations — create, update, delete",
    "Resolvers — root resolvers, resolver chain",
    "Variables & Input Types",
    "Subscriptions — real-time data",
    "Authentication & Authorization patterns",
    "N+1 Problem & DataLoader",
    "Apollo Client — useQuery, useMutation, cache",
    "Apollo Server setup",
  ],
  "next.js": [
    "Pages & File-based Routing",
    "getServerSideProps (SSR)",
    "getStaticProps & getStaticPaths (SSG)",
    "API Routes — /pages/api or App Router route handlers",
    "App Router — layouts, loading, error boundaries",
    "Server Components vs Client Components",
    "Image Optimization — next/image",
    "Middleware — edge runtime",
    "Environment Variables — .env.local",
    "Deployment on Vercel",
  ],
  nextjs: [
    "Pages & File-based Routing",
    "getServerSideProps (SSR)",
    "getStaticProps & getStaticPaths (SSG)",
    "API Routes — /pages/api or App Router route handlers",
    "App Router — layouts, loading, error boundaries",
    "Server Components vs Client Components",
    "Image Optimization — next/image",
    "Middleware — edge runtime",
    "Environment Variables — .env.local",
    "Deployment on Vercel",
  ],
  "machine learning": [
    "Types of ML — supervised, unsupervised, reinforcement",
    "Data Preprocessing — missing values, encoding, scaling",
    "Feature Engineering & Selection",
    "Linear Regression — MSE, gradient descent",
    "Logistic Regression — classification, sigmoid",
    "Decision Trees & Random Forests",
    "Support Vector Machines (SVM)",
    "Neural Network Basics — layers, activation functions, backprop",
    "Model Evaluation — accuracy, precision, recall, F1, ROC-AUC",
    "scikit-learn — fit, predict, Pipeline, GridSearchCV",
    "Overfitting & Regularization — L1, L2, dropout",
  ],
  "deep learning": [
    "Neural Network Architecture — layers, neurons, weights",
    "Activation Functions — ReLU, sigmoid, tanh, softmax",
    "Backpropagation & Gradient Descent",
    "Convolutional Neural Networks (CNNs)",
    "Recurrent Neural Networks (RNNs) & LSTM",
    "Transfer Learning — pretrained models, fine-tuning",
    "Batch Normalization & Dropout",
    "Loss Functions — cross-entropy, MSE, custom",
    "Optimizers — SGD, Adam, RMSprop",
    "PyTorch or TensorFlow/Keras basics",
  ],
  testing: [
    "Types of Testing — unit, integration, E2E",
    "Jest Basics — describe, it, expect, matchers",
    "React Testing Library — render, screen, fireEvent, userEvent",
    "Mocking — jest.mock, jest.fn, spyOn",
    "Async Testing — async/await, waitFor",
    "Test-Driven Development (TDD)",
    "Code Coverage — Istanbul/NYC",
    "End-to-End — Playwright or Cypress basics",
    "API Testing — supertest",
    "Snapshot Testing",
  ],
  security: [
    "OWASP Top 10 — XSS, CSRF, SQL Injection, IDOR, SSRF",
    "Authentication — sessions, JWT, OAuth 2.0",
    "Password Security — bcrypt, salting, PBKDF2",
    "HTTPS & TLS — certificates, Let's Encrypt",
    "Input Validation & Sanitization",
    "CORS — same-origin policy, preflight",
    "Rate Limiting & Brute-force Protection",
    "Security Headers — CSP, HSTS, X-Frame-Options",
    "Encryption — symmetric vs asymmetric, RSA, AES",
    "SAST & DAST tools",
  ],
  "data structures": [
    "Arrays & Strings — indexing, slicing, manipulation",
    "Linked Lists — singly, doubly, circular",
    "Stacks & Queues — LIFO, FIFO, use cases",
    "Hash Tables — hashing, collision resolution, load factor",
    "Binary Trees & BST — traversal (in, pre, post order)",
    "Heaps & Priority Queues — min/max heap, heapify",
    "Graphs — adjacency list/matrix, directed vs undirected",
    "BFS & DFS — graph/tree traversal",
    "Tries — prefix trees, autocomplete",
    "Segment Trees & Fenwick Trees",
  ],
  algorithms: [
    "Time & Space Complexity — Big O notation, best/worst/average",
    "Sorting — bubble, selection, insertion, merge, quick, heap",
    "Binary Search — iterative, recursive, on answer",
    "Recursion & Divide and Conquer",
    "Dynamic Programming — memoization, tabulation, classic problems",
    "Greedy Algorithms — activity selection, Huffman",
    "Backtracking — N-Queens, Sudoku, permutations",
    "Two Pointers & Sliding Window",
    "Graph Algorithms — Dijkstra, BFS, DFS, Topological Sort",
    "String Algorithms — KMP, Rabin-Karp",
  ],
  vue: [
    "Vue Instance & Options API",
    "Composition API — setup(), ref, reactive, computed",
    "Templates & Directives — v-if, v-for, v-bind, v-on, v-model",
    "Components — props, emits, slots",
    "Vue Router — routes, navigation guards, dynamic routes",
    "State Management — Pinia or Vuex",
    "Watchers & Computed Properties",
    "Lifecycle Hooks",
    "Transitions & Animations",
    "Async Components & lazy loading",
  ],
  angular: [
    "Components & Templates — @Component, template syntax",
    "Modules — NgModule, imports, declarations, providers",
    "Dependency Injection — services, providers, injectors",
    "Routing — RouterModule, ActivatedRoute, Guards",
    "Forms — Template-driven, Reactive Forms, validation",
    "HTTP Client — HttpClientModule, observables",
    "Observables & RxJS — operators: map, switchMap, combineLatest",
    "Pipes — built-in, custom pipes",
    "Change Detection — zones, OnPush strategy",
    "Angular CLI — generate, build, test",
  ],
  tailwind: [
    "Utility-First Concept — avoiding custom CSS",
    "Responsive Prefixes — sm, md, lg, xl, 2xl",
    "Flexbox Utilities — flex, items-center, justify-between, gap",
    "Grid Utilities — grid, grid-cols, col-span",
    "Spacing — p, m, px, py, space-x, space-y",
    "Typography — text-size, font-weight, tracking, leading",
    "Colors & Backgrounds — bg, text, border, gradient",
    "Dark Mode — dark: prefix, darkMode config",
    "Custom Config — tailwind.config.js, theme.extend",
    "Component Extraction — @apply, Tailwind plugins",
  ],
  postgresql: [
    "Data Types — text, integer, boolean, timestamp, jsonb, array",
    "Basic CRUD — SELECT, INSERT, UPDATE, DELETE",
    "JOINs — INNER, LEFT, FULL OUTER",
    "Indexes — B-tree, GIN, GIST, unique, partial",
    "Transactions — BEGIN, COMMIT, ROLLBACK, isolation levels",
    "Window Functions — ROW_NUMBER, RANK, LAG, LEAD",
    "CTEs — WITH clauses, recursive CTEs",
    "Stored Procedures & Functions — PL/pgSQL",
    "Full-Text Search — to_tsvector, to_tsquery",
    "JSONB Queries — operators, GIN index, containment",
  ],
  prisma: [
    "Schema Definition — models, fields, relations",
    "Relations — one-to-one, one-to-many, many-to-many",
    "CRUD with Prisma Client — findMany, create, update, delete",
    "Filtering & Sorting — where, orderBy, select, include",
    "Transactions — prisma.$transaction",
    "Migrations — prisma migrate dev, deploy, reset",
    "Prisma Studio",
    "Type Safety — generated types",
    "Raw SQL — $queryRaw, $executeRaw",
    "Connection Pooling & Performance",
  ],
  redis: [
    "Data Structures — strings, hashes, lists, sets, sorted sets",
    "CRUD — GET, SET, DEL, EXPIRE, TTL",
    "Pub/Sub — publish, subscribe",
    "Caching Patterns — cache-aside, write-through",
    "Session Storage",
    "Rate Limiting implementation",
    "Persistence — RDB vs AOF",
    "Clustering & Replication",
    "Lua Scripting",
    "Redis CLI & common commands",
  ],
  devops: [
    "Version Control — Git branching strategies, GitOps",
    "CI/CD Pipelines — GitHub Actions, Jenkins, GitLab CI",
    "Containerization — Docker, container registries",
    "Container Orchestration — Kubernetes basics",
    "Infrastructure as Code — Terraform, CloudFormation",
    "Monitoring & Logging — Prometheus, Grafana, ELK stack",
    "Load Balancing & Reverse Proxy — Nginx, HAProxy",
    "Cloud Providers — AWS/GCP/Azure core services",
    "Secret Management — Vault, AWS Secrets Manager",
    "SRE Principles — SLI, SLO, SLA, error budgets",
  ],
  "system design": [
    "Scalability — horizontal vs vertical scaling",
    "Load Balancing — round robin, consistent hashing",
    "Caching — CDN, Redis, cache eviction policies",
    "Databases — SQL vs NoSQL, sharding, replication",
    "CAP Theorem & Consistency models",
    "API Design — REST vs GraphQL vs gRPC",
    "Message Queues — Kafka, RabbitMQ, SQS",
    "Microservices vs Monolith",
    "Rate Limiting & API Gateway",
    "Designing real systems — URL shortener, chat app, news feed",
  ],
  express: [
    "Application Setup — express(), listen, middleware order",
    "Routing — app.get/post/put/delete, Router, route params",
    "Middleware — built-in, third-party, custom, error handlers",
    "Request & Response — req.body, req.params, req.query, res.json",
    "Static Files — express.static",
    "Template Engines — EJS, Pug",
    "Authentication Middleware — JWT, passport.js",
    "File Upload — multer",
    "CORS configuration",
    "Rate Limiting — express-rate-limit",
  ],
  linux: [
    "File System — ls, cd, pwd, mkdir, rm, cp, mv, find",
    "Permissions — chmod, chown, rwx, sudo",
    "Process Management — ps, top, kill, bg, fg, jobs",
    "Text Processing — grep, sed, awk, cat, head, tail",
    "Package Management — apt, yum, brew",
    "Shell Scripting — variables, loops, conditionals, functions",
    "Networking — ifconfig, netstat, ssh, scp, curl",
    "Cron Jobs — crontab, scheduling tasks",
    "Environment Variables — export, PATH, .bashrc/.zshrc",
    "Disk & Memory — df, du, free, top",
  ],
  networking: [
    "OSI & TCP/IP Models — layers and their roles",
    "IP Addressing — IPv4, IPv6, CIDR, subnetting",
    "DNS — resolution, record types (A, CNAME, MX, TXT)",
    "HTTP & HTTPS — methods, status codes, headers",
    "TCP vs UDP — connection-oriented, use cases",
    "Firewalls & NAT",
    "Load Balancers — L4 vs L7, algorithms",
    "CDN — content delivery, edge nodes",
    "VPN & Tunneling — WireGuard, OpenVPN",
    "WebSockets & Server-Sent Events",
  ],
};

/** Find topics for a skill by fuzzy-matching skill name against the keys */
export function getTopicsForSkill(skillName: string): string[] {
  const lower = skillName.toLowerCase().trim();

  // Direct match
  if (SKILL_TOPICS[lower]) return SKILL_TOPICS[lower];

  // Partial match — skill name contains key, or key contains skill name
  for (const [key, topics] of Object.entries(SKILL_TOPICS)) {
    if (lower.includes(key) || key.includes(lower)) {
      return topics;
    }
  }

  // Word-level match — any word in the skill name matches a key
  const words = lower.split(/[\s./\\-]+/);
  for (const word of words) {
    if (word.length > 2 && SKILL_TOPICS[word]) return SKILL_TOPICS[word];
  }

  return [];
}
