export interface YCCompany {
  name: string;
  batch: string;
  description: string;
  industry: string;
  url: string;
  logo?: string;
  tags: string[];
  status: "Active" | "Acquired" | "Public";
}

export const YC_BATCHES = [
  "All", "W25", "S24", "W24", "S23", "W23", "S22", "W22", "S21", "W21", "S20", "W20", "S19", "W19",
] as const;

export const ycCompaniesData: YCCompany[] = [
  {
    name: "Stripe",
    batch: "S09",
    description: "Financial infrastructure for the internet. Stripe builds economic infrastructure for the internet businesses of every size.",
    industry: "Fintech",
    url: "https://stripe.com",
    tags: ["payments", "fintech", "api", "infrastructure"],
    status: "Active",
  },
  {
    name: "Airbnb",
    batch: "W09",
    description: "A community marketplace for people to list, discover, and book unique accommodations around the world.",
    industry: "Travel & Hospitality",
    url: "https://airbnb.com",
    tags: ["marketplace", "travel", "hospitality"],
    status: "Public",
  },
  {
    name: "DoorDash",
    batch: "S13",
    description: "Technology company that connects consumers with their favorite local businesses in more than 27 countries.",
    industry: "Food & Delivery",
    url: "https://doordash.com",
    tags: ["delivery", "logistics", "marketplace"],
    status: "Public",
  },
  {
    name: "Coinbase",
    batch: "S12",
    description: "A secure online platform for buying, selling, transferring, and storing cryptocurrency.",
    industry: "Crypto & Web3",
    url: "https://coinbase.com",
    tags: ["crypto", "blockchain", "exchange", "fintech"],
    status: "Public",
  },
  {
    name: "Instacart",
    batch: "S12",
    description: "Same-day delivery and pick up service for groceries from favorite local stores.",
    industry: "E-commerce & Retail",
    url: "https://instacart.com",
    tags: ["delivery", "grocery", "marketplace"],
    status: "Public",
  },
  {
    name: "Dropbox",
    batch: "S07",
    description: "Smart workspace that transforms the way people work together, providing secure file sharing and collaboration.",
    industry: "Cloud & SaaS",
    url: "https://dropbox.com",
    tags: ["cloud", "storage", "collaboration", "productivity"],
    status: "Public",
  },
  {
    name: "Reddit",
    batch: "S05",
    description: "A network of communities where people can dive into their interests, hobbies and passions.",
    industry: "Social Media",
    url: "https://reddit.com",
    tags: ["social", "community", "forum"],
    status: "Public",
  },
  {
    name: "Twitch",
    batch: "W07",
    description: "Interactive live streaming service for content spanning gaming, entertainment, sports, music, and more.",
    industry: "Entertainment",
    url: "https://twitch.tv",
    tags: ["streaming", "gaming", "entertainment"],
    status: "Acquired",
  },
  {
    name: "Razorpay",
    batch: "W15",
    description: "India's leading full-stack financial solutions company providing payment gateway and business banking.",
    industry: "Fintech",
    url: "https://razorpay.com",
    tags: ["payments", "fintech", "india", "banking"],
    status: "Active",
  },
  {
    name: "Zerodha",
    batch: "S16",
    description: "India's largest stock broker offering free equity investments and flat ₹20 intraday and F&O trades.",
    industry: "Fintech",
    url: "https://zerodha.com",
    tags: ["trading", "fintech", "india", "stocks"],
    status: "Active",
  },
  {
    name: "Meesho",
    batch: "W16",
    description: "India's fastest-growing social commerce platform enabling small businesses to sell online.",
    industry: "E-commerce",
    url: "https://meesho.com",
    tags: ["ecommerce", "social-commerce", "india"],
    status: "Active",
  },
  {
    name: "Cleartax",
    batch: "W14",
    description: "India's largest tax and financial services software platform for individuals and businesses.",
    industry: "Fintech",
    url: "https://cleartax.in",
    tags: ["tax", "fintech", "india", "compliance"],
    status: "Active",
  },
  {
    name: "Groww",
    batch: "W18",
    description: "Investment platform enabling users to invest in mutual funds, stocks, and digital gold.",
    industry: "Fintech",
    url: "https://groww.in",
    tags: ["investing", "mutual-funds", "fintech", "india"],
    status: "Active",
  },
  {
    name: "Peppercontent",
    batch: "S21",
    description: "AI-powered content marketplace connecting brands with top freelance content creators.",
    industry: "AI & Content",
    url: "https://peppercontent.io",
    tags: ["ai", "content", "marketplace", "india"],
    status: "Active",
  },
  {
    name: "GitLab",
    batch: "W15",
    description: "The complete DevOps platform, delivered as a single application for the entire software development lifecycle.",
    industry: "Developer Tools",
    url: "https://gitlab.com",
    tags: ["devops", "git", "ci-cd", "developer-tools"],
    status: "Public",
  },
  {
    name: "Retool",
    batch: "W17",
    description: "Build internal tools remarkably fast. Retool cuts the time it takes to build internal tools in half.",
    industry: "Developer Tools",
    url: "https://retool.com",
    tags: ["low-code", "internal-tools", "developer-tools"],
    status: "Active",
  },
  {
    name: "PostHog",
    batch: "W20",
    description: "Open-source product analytics platform. Self-hosted or cloud alternative to Mixpanel and Amplitude.",
    industry: "Analytics",
    url: "https://posthog.com",
    tags: ["analytics", "open-source", "product-analytics"],
    status: "Active",
  },
  {
    name: "Cal.com",
    batch: "W24",
    description: "The open-source Calendly alternative. Self-hosted or managed scheduling infrastructure.",
    industry: "Productivity",
    url: "https://cal.com",
    tags: ["scheduling", "open-source", "productivity"],
    status: "Active",
  },
];
