import "dotenv/config";
import { prisma } from "../database/db.js";

const repos = [
  {
    name: "next.js",
    owner: "vercel",
    description: "The React Framework — Build full-stack web applications with server-side rendering, static generation, and more.",
    language: "TypeScript",
    techStack: ["React", "Node.js", "Webpack", "Turbopack"],
    difficulty: "INTERMEDIATE" as const,
    domain: "WEB" as const,
    issueTypes: ["good first issue", "bug", "feature request", "documentation"],
    stars: 127000,
    forks: 27000,
    openIssues: 2900,
    url: "https://github.com/vercel/next.js",
    tags: ["react", "ssr", "framework", "web"],
    highlights: ["One of the most popular React frameworks", "Actively maintained by Vercel", "Extensive documentation and learning resources"],
    trending: true,
  },
  {
    name: "langchain",
    owner: "langchain-ai",
    description: "Build context-aware reasoning applications with LangChain — the framework for developing apps powered by language models.",
    language: "Python",
    techStack: ["OpenAI", "HuggingFace", "Pinecone", "ChromaDB"],
    difficulty: "INTERMEDIATE" as const,
    domain: "AI" as const,
    issueTypes: ["good first issue", "enhancement", "bug"],
    stars: 98000,
    forks: 15800,
    openIssues: 1350,
    url: "https://github.com/langchain-ai/langchain",
    tags: ["ai", "llm", "nlp", "python"],
    highlights: ["Leading LLM application framework", "Rapid growth and community", "Comprehensive docs and tutorials"],
    trending: true,
  },
  {
    name: "kubernetes",
    owner: "kubernetes",
    description: "Production-Grade Container Orchestration — automate deploying, scaling, and managing containerized applications.",
    language: "Go",
    techStack: ["Docker", "etcd", "gRPC", "Prometheus"],
    difficulty: "ADVANCED" as const,
    domain: "DEVOPS" as const,
    issueTypes: ["good first issue", "kind/bug", "kind/feature"],
    stars: 112000,
    forks: 39000,
    openIssues: 2200,
    url: "https://github.com/kubernetes/kubernetes",
    tags: ["containers", "orchestration", "cloud-native", "devops"],
    highlights: ["Industry standard for container orchestration", "Massive contributor community", "CNCF graduated project"],
    trending: false,
  },
  {
    name: "flutter",
    owner: "flutter",
    description: "Google's cross-platform UI toolkit for building natively compiled applications for mobile, web, and desktop.",
    language: "Dart",
    techStack: ["Dart", "Skia", "Impeller"],
    difficulty: "BEGINNER" as const,
    domain: "MOBILE" as const,
    issueTypes: ["good first contribution", "waiting for customer response", "p: webview"],
    stars: 167000,
    forks: 27500,
    openIssues: 12500,
    url: "https://github.com/flutter/flutter",
    tags: ["mobile", "cross-platform", "dart", "ui"],
    highlights: ["Beginner-friendly with great documentation", "Single codebase for iOS, Android, Web, Desktop", "Google-backed with rich widget library"],
    trending: true,
  },
  {
    name: "vite",
    owner: "vitejs",
    description: "Next-generation frontend tooling — blazing fast dev server with instant HMR and optimized production builds.",
    language: "TypeScript",
    techStack: ["Rollup", "esbuild", "PostCSS"],
    difficulty: "BEGINNER" as const,
    domain: "WEB" as const,
    issueTypes: ["good first issue", "p3-minor-bug", "enhancement"],
    stars: 69000,
    forks: 6200,
    openIssues: 520,
    url: "https://github.com/vitejs/vite",
    tags: ["bundler", "dev-tools", "frontend", "web"],
    highlights: ["Extremely fast build tool", "Easy to contribute — well organized codebase", "Framework-agnostic"],
    trending: false,
  },
  {
    name: "prisma",
    owner: "prisma",
    description: "Next-generation ORM for Node.js and TypeScript — type-safe database access with auto-generated query builder.",
    language: "TypeScript",
    techStack: ["Rust", "Node.js", "PostgreSQL", "MySQL", "SQLite"],
    difficulty: "INTERMEDIATE" as const,
    domain: "DATA" as const,
    issueTypes: ["good first issue", "bug/0-still-open", "kind/feature"],
    stars: 40000,
    forks: 1560,
    openIssues: 3100,
    url: "https://github.com/prisma/prisma",
    tags: ["orm", "database", "typescript", "node"],
    highlights: ["Modern type-safe ORM", "Great for TypeScript developers", "Active community and frequent releases"],
    trending: false,
  },
  {
    name: "react",
    owner: "facebook",
    description: "The library for web and native user interfaces. Build UIs from individual pieces called components.",
    language: "JavaScript",
    techStack: ["JSX", "Fiber", "Reconciler"],
    difficulty: "ADVANCED" as const,
    domain: "WEB" as const,
    issueTypes: ["good first issue", "Component: Hooks", "React 19"],
    stars: 230000,
    forks: 47000,
    openIssues: 900,
    url: "https://github.com/facebook/react",
    tags: ["ui", "library", "components", "frontend"],
    highlights: ["Most popular UI library in the world", "Powers millions of applications", "Well-documented with huge ecosystem"],
    trending: true,
  },
  {
    name: "tensorflow",
    owner: "tensorflow",
    description: "An open source machine learning framework for everyone. Build and deploy ML models at scale.",
    language: "Python",
    techStack: ["C++", "CUDA", "Keras", "NumPy"],
    difficulty: "ADVANCED" as const,
    domain: "AI" as const,
    issueTypes: ["good first issue", "stat:awaiting response", "type:feature"],
    stars: 186000,
    forks: 74000,
    openIssues: 1800,
    url: "https://github.com/tensorflow/tensorflow",
    tags: ["machine-learning", "deep-learning", "neural-network", "ai"],
    highlights: ["Industry standard for ML", "Google-backed with enterprise support", "GSoC participating organization"],
    trending: false,
  },
  {
    name: "rust",
    owner: "rust-lang",
    description: "Empowering everyone to build reliable and efficient software. A language for performance and safety.",
    language: "Rust",
    techStack: ["LLVM", "Cargo"],
    difficulty: "ADVANCED" as const,
    domain: "OTHER" as const,
    issueTypes: ["E-easy", "E-mentor", "E-help-wanted"],
    stars: 99000,
    forks: 12700,
    openIssues: 9500,
    url: "https://github.com/rust-lang/rust",
    tags: ["systems", "programming-language", "memory-safety", "performance"],
    highlights: ["Most loved programming language (Stack Overflow)", "Strong mentorship culture", "Excellent contributor documentation"],
    trending: false,
  },
  {
    name: "supabase",
    owner: "supabase",
    description: "The open source Firebase alternative. Build production-grade applications with a Postgres database, Auth, APIs, and more.",
    language: "TypeScript",
    techStack: ["PostgreSQL", "PostgREST", "GoTrue", "Realtime"],
    difficulty: "BEGINNER" as const,
    domain: "WEB" as const,
    issueTypes: ["good first issue", "bug", "enhancement"],
    stars: 74000,
    forks: 7200,
    openIssues: 430,
    url: "https://github.com/supabase/supabase",
    tags: ["backend", "baas", "postgres", "realtime"],
    highlights: ["Beginner-friendly codebase", "Active Discord community", "Modern tech stack with TypeScript"],
    trending: true,
  },
  {
    name: "deno",
    owner: "denoland",
    description: "A modern runtime for JavaScript and TypeScript with secure defaults and great developer experience.",
    language: "Rust",
    techStack: ["V8", "Tokio", "TypeScript"],
    difficulty: "ADVANCED" as const,
    domain: "WEB" as const,
    issueTypes: ["good first issue", "bug", "feat"],
    stars: 98000,
    forks: 5400,
    openIssues: 1800,
    url: "https://github.com/denoland/deno",
    tags: ["runtime", "javascript", "typescript", "rust"],
    highlights: ["Built in Rust for performance", "Secure by default", "Compatible with Node.js ecosystem"],
    trending: false,
  },
  {
    name: "appwrite",
    owner: "appwrite",
    description: "Your backend, minus the hassle. Build secure and scalable backend APIs for web, mobile, and Flutter.",
    language: "TypeScript",
    techStack: ["Node.js", "MariaDB", "Redis", "Docker"],
    difficulty: "BEGINNER" as const,
    domain: "WEB" as const,
    issueTypes: ["good first issue", "bug", "feature"],
    stars: 45000,
    forks: 4000,
    openIssues: 700,
    url: "https://github.com/appwrite/appwrite",
    tags: ["backend", "baas", "self-hosted", "api"],
    highlights: ["Very beginner-friendly community", "Hacktoberfest regular participant", "Great documentation"],
    trending: false,
  },
  {
    name: "pytorch",
    owner: "pytorch",
    description: "Tensors and dynamic neural networks in Python with strong GPU acceleration. The go-to framework for AI research.",
    language: "Python",
    techStack: ["C++", "CUDA", "cuDNN"],
    difficulty: "ADVANCED" as const,
    domain: "AI" as const,
    issueTypes: ["good first issue", "module: nn", "triaged"],
    stars: 84000,
    forks: 22600,
    openIssues: 13000,
    url: "https://github.com/pytorch/pytorch",
    tags: ["deep-learning", "tensors", "gpu", "research"],
    highlights: ["Preferred framework for AI research", "Meta-backed with strong community", "Excellent documentation"],
    trending: true,
  },
  {
    name: "grafana",
    owner: "grafana",
    description: "The open and composable observability and data visualization platform. Visualize metrics from every source.",
    language: "Go",
    techStack: ["React", "Go", "Prometheus", "Loki"],
    difficulty: "INTERMEDIATE" as const,
    domain: "DEVOPS" as const,
    issueTypes: ["good first issue", "type/bug", "type/feature-request"],
    stars: 65000,
    forks: 12000,
    openIssues: 4200,
    url: "https://github.com/grafana/grafana",
    tags: ["monitoring", "visualization", "dashboards", "observability"],
    highlights: ["Industry standard for observability", "Full-stack contributions (Go + React)", "Well-organized issue tracker"],
    trending: false,
  },
  {
    name: "svelte",
    owner: "sveltejs",
    description: "Cybernetically enhanced web apps. A new approach to building user interfaces with a compiler-based framework.",
    language: "JavaScript",
    techStack: ["Compiler", "SvelteKit", "Vite"],
    difficulty: "INTERMEDIATE" as const,
    domain: "WEB" as const,
    issueTypes: ["good first issue", "bug", "feature request"],
    stars: 80000,
    forks: 4200,
    openIssues: 800,
    url: "https://github.com/sveltejs/svelte",
    tags: ["compiler", "framework", "ui", "frontend"],
    highlights: ["Innovative compiler-based approach", "Small bundle sizes", "Growing ecosystem with SvelteKit"],
    trending: true,
  },
  {
    name: "compose",
    owner: "docker",
    description: "Define and run multi-container applications with Docker. Simplify development and deployment workflows.",
    language: "Go",
    techStack: ["Docker", "containerd", "BuildKit"],
    difficulty: "INTERMEDIATE" as const,
    domain: "DEVOPS" as const,
    issueTypes: ["good first issue", "kind/bug", "kind/enhancement"],
    stars: 34000,
    forks: 5200,
    openIssues: 300,
    url: "https://github.com/docker/compose",
    tags: ["containers", "docker", "orchestration", "development"],
    highlights: ["Essential developer tool", "Well-documented codebase", "Part of the Docker ecosystem"],
    trending: false,
  },
  {
    name: "scikit-learn",
    owner: "scikit-learn",
    description: "Machine learning in Python. Simple and efficient tools for predictive data analysis, built on NumPy and SciPy.",
    language: "Python",
    techStack: ["NumPy", "SciPy", "Cython"],
    difficulty: "INTERMEDIATE" as const,
    domain: "DATA" as const,
    issueTypes: ["good first issue", "Bug", "Enhancement"],
    stars: 60000,
    forks: 25200,
    openIssues: 1700,
    url: "https://github.com/scikit-learn/scikit-learn",
    tags: ["machine-learning", "data-science", "statistics", "python"],
    highlights: ["Gold standard for classical ML", "Excellent contributor guide", "Mentor-friendly community"],
    trending: false,
  },
  {
    name: "react-native",
    owner: "facebook",
    description: "A framework for building native applications using React. Write once, deploy to iOS and Android.",
    language: "Java",
    techStack: ["React", "Hermes", "Fabric", "TurboModules"],
    difficulty: "INTERMEDIATE" as const,
    domain: "MOBILE" as const,
    issueTypes: ["good first issue", "Bug", "Feature Request"],
    stars: 119000,
    forks: 24200,
    openIssues: 800,
    url: "https://github.com/facebook/react-native",
    tags: ["mobile", "react", "ios", "android"],
    highlights: ["Build native mobile apps with React", "Meta-backed with huge community", "Rich third-party ecosystem"],
    trending: false,
  },
  {
    name: "excalidraw",
    owner: "excalidraw",
    description: "Virtual whiteboard for sketching hand-drawn like diagrams. Collaborative and open source.",
    language: "TypeScript",
    techStack: ["React", "Canvas", "WebSocket"],
    difficulty: "BEGINNER" as const,
    domain: "WEB" as const,
    issueTypes: ["good first issue", "bug", "feature request"],
    stars: 85000,
    forks: 8000,
    openIssues: 1200,
    url: "https://github.com/excalidraw/excalidraw",
    tags: ["drawing", "whiteboard", "collaboration", "canvas"],
    highlights: ["Fun project to contribute to", "Beginner-friendly with clear issues", "Active and welcoming community"],
    trending: true,
  },
  {
    name: "astro",
    owner: "withastro",
    description: "The web framework for content-driven websites. Ship less JavaScript and build faster sites.",
    language: "TypeScript",
    techStack: ["Vite", "Rollup", "MDX"],
    difficulty: "BEGINNER" as const,
    domain: "WEB" as const,
    issueTypes: ["good first issue", "bug", "feat"],
    stars: 47000,
    forks: 2500,
    openIssues: 200,
    url: "https://github.com/withastro/astro",
    tags: ["ssg", "framework", "performance", "content"],
    highlights: ["Innovative island architecture", "Great for content sites", "Friendly contributor community"],
    trending: true,
  },
];

async function seedOpenSourceRepos() {
  console.log("Seeding open source repositories...");

  // Delete existing repos and re-create
  await prisma.opensourceRepo.deleteMany();

  await prisma.opensourceRepo.createMany({
    data: repos,
  });

  console.log(`Seeded ${repos.length} open source repositories.`);
}

seedOpenSourceRepos()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
