import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

const connectionString = process.env["DATABASE_URL"] ?? "";
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

const internships = [
  // ═══ CENTRAL GOVERNMENT & POLICY ═══
  { name: "Ministry of External Affairs (MEA)", category: "Central Government & Policy", timeline: "Apr–Sep | Oct–Mar (2026)", organizer: "Govt of India (MEA)", domain: "Foreign Policy, International Relations, Research", stipend: "₹10,000 – ₹15,000 / month", eligibility: "UG/PG (any stream)", reality: "Brand value > money. Serious policy exposure." },
  { name: "NITI Aayog", category: "Central Government & Policy", timeline: "Monthly intakes (2026)", organizer: "NITI Aayog", domain: "Policy, Economics, Data, AI", stipend: "Unpaid", eligibility: "UG/PG (top profiles preferred)", reality: "Unpaid but opens elite doors." },
  { name: "Prime Minister Internship Scheme (PMIS)", category: "Central Government & Policy", timeline: "Annual intake (2026)", organizer: "Ministry of Corporate Affairs", domain: "Corporate, Govt Projects, CSR", stipend: "₹12,000+", eligibility: "UG/PG (All India)", reality: "Massive seats. Good for freshers." },
  { name: "Ministry of Women & Child Development", category: "Central Government & Policy", timeline: "Quarterly (2026)", organizer: "MWCD, Govt of India", domain: "Research, Policy, Social Data", stipend: "₹10,000 – ₹20,000", eligibility: "Women UG/PG", reality: "Paid + low competition." },
  { name: "National Human Rights Commission (NHRC)", category: "Central Government & Policy", timeline: "Summer & Winter 2026", organizer: "NHRC", domain: "Law, Human Rights, Policy", stipend: "₹12,000", eligibility: "Law / Social Science students", reality: "Field exposure. Serious documentation work." },
  { name: "Lok Sabha Secretariat", category: "Central Government & Policy", timeline: "Jan–Mar | Jun–Aug 2026", organizer: "Parliament of India", domain: "Parliamentary Research, Governance", stipend: "Unpaid", eligibility: "PG preferred", reality: "Prestige internship. Tough entry." },
  { name: "Rajya Sabha Secretariat", category: "Central Government & Policy", timeline: "Rolling (2026)", organizer: "Rajya Sabha Secretariat", domain: "Policy Research, Documentation", stipend: "Unpaid", eligibility: "PG / Research students", reality: "Hardcore policy work." },
  { name: "Press Information Bureau (PIB)", category: "Central Government & Policy", timeline: "Annual (2026)", organizer: "PIB, Govt of India", domain: "Media, Communication, Content", stipend: "₹10,000 – ₹15,000", eligibility: "Journalism / Any UG", reality: "Media credibility boost." },
  { name: "UIDAI (Aadhaar)", category: "Central Government & Policy", timeline: "Feb–Jul 2026", organizer: "UIDAI", domain: "IT, Data Analytics, Cybersecurity", stipend: "₹15,000", eligibility: "BTech/MTech/MCA/Data", reality: "Tech + Govt = rare combo." },
  { name: "MOSPI (Statistics Ministry)", category: "Central Government & Policy", timeline: "Rolling (2026)", organizer: "Ministry of Statistics", domain: "Data Analysis, Economics, Surveys", stipend: "₹10,000+", eligibility: "Stats / Eco / Data students", reality: "Real datasets, not theory." },
  { name: "Election Commission of India", category: "Central Government & Policy", timeline: "Pre-election cycles", organizer: "ECI", domain: "Governance, Data, Admin", stipend: "₹10,000", eligibility: "UG/PG", reality: "High responsibility, zero PR." },
  { name: "National Informatics Centre (NIC)", category: "Central Government & Policy", timeline: "Rolling (2026)", organizer: "NIC", domain: "Govt IT Systems, Software", stipend: "₹10,000 – ₹15,000", eligibility: "CS/IT/ECE", reality: "Backbone of govt tech." },
  { name: "Ministry of Corporate Affairs", category: "Central Government & Policy", timeline: "Annual", organizer: "MCA", domain: "Corporate Law, Compliance", stipend: "₹12,000", eligibility: "Law / Commerce", reality: "Policy + legal exposure." },
  { name: "Ministry of Electronics & IT (MeitY)", category: "Central Government & Policy", timeline: "Rolling", organizer: "MeitY", domain: "AI, Cybersecurity, IT Policy", stipend: "₹15,000+", eligibility: "Tech background", reality: "Future-facing ministry." },
  { name: "Atal Innovation Mission", category: "Central Government & Policy", timeline: "Quarterly", organizer: "NITI Aayog", domain: "Innovation, Startups", stipend: "₹10,000+", eligibility: "UG/PG", reality: "Startup ecosystem access." },
  { name: "MyGov India", category: "Central Government & Policy", timeline: "Rolling", organizer: "Govt of India", domain: "Content, Policy Tech", stipend: "₹10,000", eligibility: "Any UG", reality: "Visibility > money." },
  { name: "Department of Science & Technology", category: "Central Government & Policy", timeline: "Annual", organizer: "DST", domain: "R&D, Research Policy", stipend: "₹15,000+", eligibility: "STEM students", reality: "Research-heavy." },
  { name: "Central Vigilance Commission", category: "Central Government & Policy", timeline: "Annual", organizer: "CVC", domain: "Governance, Audit", stipend: "₹10,000", eligibility: "UG/PG", reality: "Serious admin exposure." },
  { name: "Planning Departments (Central/State)", category: "Central Government & Policy", timeline: "Mid-2026", organizer: "Govt Planning Bodies", domain: "Economics, Policy, Data", stipend: "₹8,000 – ₹12,000", eligibility: "PG preferred", reality: "Low hype, high learning." },
  { name: "Ministry of Labour & Employment", category: "Central Government & Policy", timeline: "Annual", organizer: "Govt of India", domain: "Labour Policy, Data", stipend: "₹10,000", eligibility: "UG/PG", reality: "Policy depth, less competition." },

  // ═══ PSU, BANKING & FINANCE ═══
  { name: "Reserve Bank of India (RBI)", category: "PSU, Banking & Finance", timeline: "Summer 2026 (May–July)", organizer: "RBI", domain: "Banking, Economics, FinTech, Research", stipend: "₹20,000 / month", eligibility: "UG/PG (Eco/Finance/Tech preferred)", reality: "Brand > money. Very selective." },
  { name: "Securities and Exchange Board of India (SEBI)", category: "PSU, Banking & Finance", timeline: "Rolling (2026)", organizer: "SEBI", domain: "Markets, Law, Compliance, Analytics", stipend: "₹15,000 / month", eligibility: "UG/PG (Law/Finance/Management)", reality: "Finance careers accelerator." },
  { name: "Insurance Regulatory and Development Authority of India (IRDAI)", category: "PSU, Banking & Finance", timeline: "Annual (2026)", organizer: "IRDAI", domain: "Insurance, Risk, Policy", stipend: "₹15,000", eligibility: "UG/PG (Commerce/Eco/Maths)", reality: "Niche but high-value exposure." },
  { name: "National Payments Corporation of India (NPCI)", category: "PSU, Banking & Finance", timeline: "Mid-2026", organizer: "NPCI", domain: "FinTech, Payments, Data", stipend: "₹20,000 – ₹25,000", eligibility: "CS/IT/Finance", reality: "Real-world systems, high impact." },
  { name: "State Bank of India (SBI)", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "SBI", domain: "Banking Ops, Analytics", stipend: "₹10,000 – ₹15,000", eligibility: "UG/PG", reality: "Scale exposure, structured work." },
  { name: "HDFC Bank", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "HDFC Bank", domain: "Finance, Analytics, Product", stipend: "₹15,000+", eligibility: "Commerce/MBA/Data", reality: "Performance-driven." },
  { name: "ICICI Bank", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "ICICI Bank", domain: "Finance, Risk, Data", stipend: "₹15,000+", eligibility: "Commerce/MBA/Data", reality: "Fast-paced corporate learning." },
  { name: "Axis Bank", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "Axis Bank", domain: "Analytics, Ops, Finance", stipend: "₹15,000+", eligibility: "UG/PG", reality: "KPI-driven environment." },
  { name: "Bandhan Bank", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "Bandhan Bank", domain: "Banking, Analytics, Ops", stipend: "₹12,000 – ₹20,000", eligibility: "UG/PG", reality: "Strong regional exposure." },
  { name: "Life Insurance Corporation of India (LIC)", category: "PSU, Banking & Finance", timeline: "Annual (2026)", organizer: "LIC", domain: "Insurance, Actuarial, Ops", stipend: "₹10,000 – ₹15,000", eligibility: "Commerce/Maths", reality: "PSU discipline, huge scale." },
  { name: "NTPC", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "NTPC", domain: "Power, Electrical, Ops", stipend: "₹15,000", eligibility: "Engineering", reality: "Industrial exposure." },
  { name: "ONGC", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "ONGC", domain: "Energy, Geology, Ops", stipend: "₹15,000", eligibility: "Engineering/Geology", reality: "Field + desk learning." },
  { name: "Indian Oil Corporation", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "IOCL", domain: "Chemical, Ops, Supply Chain", stipend: "₹15,000", eligibility: "Engineering", reality: "Process-heavy PSU." },
  { name: "Bharat Petroleum", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "BPCL", domain: "Mechanical, Ops, Retail", stipend: "₹15,000", eligibility: "Engineering/MBA", reality: "Operations exposure." },
  { name: "Hindustan Petroleum", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "HPCL", domain: "Mechanical, Chemical, Ops", stipend: "₹15,000", eligibility: "Engineering", reality: "Structured PSU work." },
  { name: "GAIL", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "GAIL", domain: "Gas, Energy, Projects", stipend: "₹15,000", eligibility: "Engineering", reality: "Infrastructure exposure." },
  { name: "Coal India Limited", category: "PSU, Banking & Finance", timeline: "Summer 2026", organizer: "CIL", domain: "Mining, Ops, Data", stipend: "₹15,000", eligibility: "Engineering/Geology", reality: "PSU scale, tough environment." },
  { name: "Power Finance Corporation", category: "PSU, Banking & Finance", timeline: "Annual (2026)", organizer: "PFC", domain: "Infrastructure Finance", stipend: "₹15,000 – ₹20,000", eligibility: "Finance/MBA", reality: "Infra funding exposure." },
  { name: "Rural Electrification Corporation", category: "PSU, Banking & Finance", timeline: "Annual (2026)", organizer: "REC", domain: "Energy Finance", stipend: "₹15,000 – ₹20,000", eligibility: "Finance/Engineering", reality: "Project finance learning." },
  { name: "Export-Import Bank of India", category: "PSU, Banking & Finance", timeline: "Annual (2026)", organizer: "EXIM Bank", domain: "International Finance, Trade", stipend: "₹20,000+", eligibility: "MBA/Eco/Finance", reality: "Elite finance exposure." },

  // ═══ IITs, IIMs, IISc, ISI & ELITE ACADEMIA ═══
  { name: "Indian Institute of Science (IISc), Bengaluru", category: "IITs, IIMs, IISc & Elite Academia", timeline: "May–July 2026", organizer: "IISc", domain: "AI, ML, Core Research, Systems", stipend: "₹20,000 – ₹25,000", eligibility: "Top UG/PG (STEM)", reality: "Research-heavy. No spoon-feeding." },
  { name: "Indian Institute of Technology Bombay (IIT-B)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIT Bombay", domain: "AI, Robotics, Core Engineering", stipend: "₹20,000", eligibility: "UG/PG (STEM)", reality: "Merit-only. Strong recommendations help." },
  { name: "Indian Institute of Technology Delhi (IIT-D)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "May–July 2026", organizer: "IIT Delhi", domain: "AI, Data, Robotics, Research", stipend: "₹20,000", eligibility: "UG/PG", reality: "Competitive labs. Prior projects matter." },
  { name: "Indian Institute of Technology Madras (IIT-M)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIT Madras", domain: "AI, Systems, Core Engineering", stipend: "₹20,000", eligibility: "UG/PG", reality: "Research output expected." },
  { name: "Indian Institute of Technology Kanpur (IIT-K)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIT Kanpur", domain: "CS, Maths, Core Research", stipend: "₹20,000", eligibility: "UG/PG", reality: "Strong fundamentals required." },
  { name: "Indian Institute of Technology Kharagpur (IIT-KGP)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "May–July 2026", organizer: "IIT Kharagpur", domain: "Core Engineering, AI, Research", stipend: "₹20,000", eligibility: "UG/PG", reality: "Long projects, serious commitment." },
  { name: "Indian Institute of Technology Gandhinagar (IIT-GN)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIT Gandhinagar", domain: "Research, Interdisciplinary Tech", stipend: "₹20,000", eligibility: "UG/PG", reality: "Smaller campus, deep research." },
  { name: "Indian Institute of Technology Indore (IIT-I)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIT Indore", domain: "AI, ML, Core Engineering", stipend: "₹20,000", eligibility: "UG/PG", reality: "Research-driven environment." },
  { name: "Indian Institute of Management Ahmedabad (IIM-A)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIM Ahmedabad", domain: "Consulting, Strategy, Research", stipend: "₹25,000", eligibility: "UG/PG (Top profiles)", reality: "Brand value > stipend." },
  { name: "Indian Institute of Management Bangalore (IIM-B)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIM Bangalore", domain: "Analytics, Management, Strategy", stipend: "₹25,000", eligibility: "UG/PG", reality: "Corporate-ready exposure." },
  { name: "Indian Institute of Management Calcutta (IIM-C)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIM Calcutta", domain: "Finance, Analytics, Research", stipend: "₹25,000", eligibility: "UG/PG", reality: "Finance-heavy, intense learning." },
  { name: "Indian Institute of Management Indore (IIM-I)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIM Indore", domain: "Management, Ops, Analytics", stipend: "₹20,000", eligibility: "UG/PG", reality: "Structured corporate exposure." },
  { name: "Indian Statistical Institute (ISI), Kolkata", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "ISI", domain: "Statistics, Data Science, AI", stipend: "₹20,000", eligibility: "Maths/Stats/CS", reality: "Concept-heavy. Zero hand-holding." },
  { name: "Indian Institutes of Science Education & Research (IISERs)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IISERs (All campuses)", domain: "Pure Science, Research", stipend: "₹15,000", eligibility: "Science UG/PG", reality: "Research mindset mandatory." },
  { name: "IIIT Hyderabad", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIIT Hyderabad", domain: "AI, Systems, Robotics", stipend: "₹25,000", eligibility: "CS/IT/STEM", reality: "Skills > CGPA." },
  { name: "IIIT Bangalore", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "IIIT Bangalore", domain: "Data Science, AI", stipend: "₹20,000", eligibility: "CS/IT/Data", reality: "Industry-linked research." },
  { name: "NIT Tiruchirappalli (NIT-T)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "NIT Trichy", domain: "Core Engineering, Research", stipend: "₹15,000", eligibility: "UG/PG", reality: "Strong academic culture." },
  { name: "NIT Surathkal (NIT-K)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "NITK Surathkal", domain: "Engineering, Research", stipend: "₹15,000", eligibility: "UG/PG", reality: "Competitive labs." },
  { name: "NIT Calicut (NIT-C)", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "NIT Calicut", domain: "Research, Core Engineering", stipend: "₹15,000", eligibility: "UG/PG", reality: "Research-focused." },
  { name: "BITS Pilani", category: "IITs, IIMs, IISc & Elite Academia", timeline: "Summer 2026", organizer: "BITS Pilani", domain: "Tech, Research, Product", stipend: "₹20,000", eligibility: "UG/PG", reality: "Industry-relevant projects." },

  // ═══ TOP TECH & MNC INTERNSHIPS ═══
  { name: "Google", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Google India", domain: "SDE, AI/ML, Data, Product", stipend: "₹80,000+ / month", eligibility: "Top CS profiles", reality: "Brutal interviews. Brand is unmatched." },
  { name: "Microsoft", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Microsoft IDC India", domain: "Software, Cloud, AI", stipend: "₹60,000+", eligibility: "CS/IT", reality: "PPO possible if you deliver." },
  { name: "Amazon", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Amazon India", domain: "SDE, Data, Ops", stipend: "₹60,000+", eligibility: "Strong DSA", reality: "High workload, high payoff." },
  { name: "Apple", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Apple India", domain: "Hardware, Software, Design", stipend: "₹70,000+", eligibility: "Elite profiles", reality: "Small intake, premium brand." },
  { name: "Meta", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Meta India", domain: "Software, Data, Product", stipend: "₹70,000+", eligibility: "Top-tier engineers", reality: "Research-heavy interviews." },
  { name: "NVIDIA", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "NVIDIA India", domain: "AI, GPU, Systems", stipend: "₹80,000+", eligibility: "CS/ECE", reality: "Hardcore systems knowledge." },
  { name: "Qualcomm", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Qualcomm India", domain: "Embedded, Telecom, AI", stipend: "₹60,000+", eligibility: "ECE/CS", reality: "Core engineering focus." },
  { name: "Intel", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Intel India", domain: "Hardware, Systems, AI", stipend: "₹60,000+", eligibility: "CS/ECE", reality: "Strong fundamentals needed." },
  { name: "Samsung R&D Institute India", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Samsung R&D India", domain: "Software, AI, Mobile Systems", stipend: "₹40,000+", eligibility: "CS/IT", reality: "Product-driven work." },
  { name: "Adobe", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Adobe India", domain: "Software, UX, Data", stipend: "₹50,000+", eligibility: "CS/Design", reality: "Creativity + engineering." },
  { name: "IBM", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "IBM India", domain: "Cloud, AI, Enterprise Systems", stipend: "₹35,000+", eligibility: "CS/IT", reality: "Enterprise exposure." },
  { name: "Oracle", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Oracle India", domain: "Databases, Cloud", stipend: "₹40,000+", eligibility: "CS/IT", reality: "Database-heavy roles." },
  { name: "SAP", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "SAP Labs India", domain: "ERP, Analytics, Cloud", stipend: "₹35,000+", eligibility: "CS/IT", reality: "Enterprise products learning." },
  { name: "Flipkart", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Flipkart", domain: "Product, SDE, Data", stipend: "₹40,000+", eligibility: "CS/IT", reality: "Fast-paced startup culture." },
  { name: "Meesho", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Meesho", domain: "Backend, Data, Product", stipend: "₹30,000+", eligibility: "CS/IT", reality: "Ownership from day one." },
  { name: "Swiggy", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Swiggy", domain: "Backend, Data, Ops", stipend: "₹35,000+", eligibility: "CS/IT", reality: "Production-scale systems." },
  { name: "Zomato", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Zomato", domain: "Software, Analytics", stipend: "₹25,000+", eligibility: "CS/IT", reality: "Data-driven culture." },
  { name: "Ola", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Ola", domain: "Mobility Tech, Backend", stipend: "₹30,000+", eligibility: "CS/IT", reality: "Scale + chaos." },
  { name: "Zoho", category: "Top Tech & MNC", timeline: "Year-round 2026", organizer: "Zoho", domain: "SaaS, Product, Support", stipend: "₹25,000+", eligibility: "Any discipline (skills matter)", reality: "Degree < skills." },
  { name: "Freshworks", category: "Top Tech & MNC", timeline: "Summer 2026", organizer: "Freshworks", domain: "SaaS, Product, Engineering", stipend: "₹30,000+", eligibility: "CS/IT", reality: "Modern SaaS exposure." },

  // ═══ SPACE, DEFENCE, CONSULTING & GLOBAL ═══
  { name: "Indian Space Research Organisation (ISRO)", category: "Space, Defence, Consulting & Global", timeline: "Summer & Winter 2026", organizer: "ISRO (Multiple Centres)", domain: "Space Tech, Data, Aerospace", stipend: "₹10,000 – ₹15,000", eligibility: "STEM UG/PG", reality: "Slow process. Massive credibility." },
  { name: "Defence Research and Development Organisation (DRDO)", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "DRDO Labs", domain: "Defence R&D, AI, Materials", stipend: "₹10,000 – ₹15,000", eligibility: "Engineering/Science", reality: "Research-heavy. Security checks apply." },
  { name: "Bharat Electronics Limited (BEL)", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "BEL (PSU)", domain: "Embedded, Defence Electronics", stipend: "₹10,000 – ₹15,000", eligibility: "ECE/CS", reality: "Core electronics exposure." },
  { name: "Hindustan Aeronautics Limited (HAL)", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "HAL", domain: "Aerospace, Mechanical, QA", stipend: "₹10,000 – ₹15,000", eligibility: "Engineering", reality: "PSU discipline. Strong processes." },
  { name: "Tata Consultancy Services (TCS)", category: "Space, Defence, Consulting & Global", timeline: "Summer / Pre-final 2026", organizer: "TCS", domain: "Software, Data, AI", stipend: "₹10,000 – ₹20,000", eligibility: "Engineering", reality: "PPO possible if you deliver." },
  { name: "Infosys", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "Infosys", domain: "IT, Systems, Data", stipend: "₹15,000+", eligibility: "Engineering", reality: "Structured corporate training." },
  { name: "Wipro", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "Wipro", domain: "IT Services, Cloud", stipend: "₹12,000 – ₹18,000", eligibility: "Engineering", reality: "Service-industry exposure." },
  { name: "Deloitte", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "Deloitte India", domain: "Consulting, Analytics, Risk", stipend: "₹20,000 – ₹30,000", eligibility: "UG/PG", reality: "Corporate polish required." },
  { name: "PwC India", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "PwC India", domain: "Audit, Consulting, Data", stipend: "₹20,000 – ₹30,000", eligibility: "UG/PG", reality: "Client-facing pressure." },
  { name: "EY India", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "EY India", domain: "Consulting, Analytics", stipend: "₹20,000 – ₹30,000", eligibility: "UG/PG", reality: "Long hours, steep learning." },
  { name: "KPMG India", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "KPMG India", domain: "Advisory, Risk, Data", stipend: "₹20,000 – ₹30,000", eligibility: "UG/PG", reality: "Consulting mindset needed." },
  { name: "Boston Consulting Group (BCG)", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "BCG India", domain: "Strategy, Analytics", stipend: "₹1,00,000+", eligibility: "Elite campuses", reality: "Case interviews are brutal." },
  { name: "McKinsey & Company", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "McKinsey India", domain: "Strategy, Operations", stipend: "₹1,00,000+", eligibility: "Elite profiles only", reality: "Top 1% selection." },
  { name: "United Nations Development Programme (UNDP)", category: "Space, Defence, Consulting & Global", timeline: "Rolling (2026)", organizer: "UNDP India", domain: "Development, Policy, Data", stipend: "₹10,000 – ₹15,000", eligibility: "UG/PG", reality: "Impact > pay." },
  { name: "UNICEF India", category: "Space, Defence, Consulting & Global", timeline: "Rolling", organizer: "UNICEF India", domain: "Child Policy, Data, Programmes", stipend: "₹10,000 – ₹15,000", eligibility: "UG/PG", reality: "Field + desk work." },
  { name: "World Bank", category: "Space, Defence, Consulting & Global", timeline: "Summer 2026", organizer: "World Bank India", domain: "Economics, Development Finance", stipend: "₹25,000+", eligibility: "PG preferred", reality: "Global policy exposure." },
  { name: "Startup India", category: "Space, Defence, Consulting & Global", timeline: "Rolling", organizer: "DPIIT", domain: "Startups, Policy, Innovation", stipend: "₹10,000+", eligibility: "UG/PG", reality: "Ecosystem access." },
  { name: "T-Hub", category: "Space, Defence, Consulting & Global", timeline: "Year-round 2026", organizer: "T-Hub", domain: "Startups, Product, VC", stipend: "₹10,000 – ₹20,000", eligibility: "UG/PG", reality: "Network > stipend." },
  { name: "Kerala Startup Mission", category: "Space, Defence, Consulting & Global", timeline: "Year-round", organizer: "Govt of Kerala", domain: "Startups, Product, Innovation", stipend: "₹10,000 – ₹20,000", eligibility: "UG/PG", reality: "Rapid learning curve." },
  { name: "Maharashtra State Innovation Society", category: "Space, Defence, Consulting & Global", timeline: "Rolling", organizer: "Govt of Maharashtra", domain: "Innovation, Policy, Startups", stipend: "₹10,000 – ₹20,000", eligibility: "UG/PG", reality: "Policy + startup mix." },
];

async function main() {
  await prisma.govInternship.deleteMany();
  const result = await prisma.govInternship.createMany({ data: internships });
  console.log(`Seeded ${result.count} government internships`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
