import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

const connectionString = process.env["DATABASE_URL"] ?? "";
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

const puneCompanies = [
  // ── Large IT Services & MNCs ──────────────────────────────────────
  {
    name: "Persistent Systems",
    slug: "persistent-systems",
    description:
      "Persistent Systems is a global technology services company headquartered in Pune. They specialize in software product development, digital transformation, and enterprise modernization for ISVs and enterprises worldwide.",
    industry: "IT Services",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Bhageerath, 402 Senapati Bapat Road, Pune 411016",
    website: "https://www.persistent.com",
    technologies: ["Java", "Azure", "Salesforce", "AWS", "React", "Node.js", "AI/ML"],
    hiringStatus: true,
    foundedYear: 1990,
    socialLinks: { linkedin: "https://linkedin.com/company/persistent-systems" },
  },
  {
    name: "Zensar Technologies",
    slug: "zensar-technologies",
    description:
      "Zensar Technologies is an RPG Group company providing digital solutions, technology services, and experience-led engineering. Headquartered in Pune, they serve clients across retail, banking, insurance, and manufacturing.",
    industry: "IT Services",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Zensar Knowledge Park, Kharadi, Pune 411014",
    website: "https://www.zensar.com",
    technologies: ["Java", "Salesforce", "AWS", "Azure", "Oracle", "SAP", "React"],
    hiringStatus: true,
    foundedYear: 1991,
    socialLinks: { linkedin: "https://linkedin.com/company/zensar-technologies" },
  },
  {
    name: "KPIT Technologies",
    slug: "kpit-technologies",
    description:
      "KPIT Technologies is a global partner to the automotive and mobility ecosystem, providing embedded software, AI, and autonomous driving solutions. Headquartered in Pune, they work with leading OEMs worldwide.",
    industry: "Automotive Software",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Plot 17, Rajiv Gandhi Infotech Park, Hinjewadi Phase 1, Pune 411057",
    website: "https://www.kpit.com",
    technologies: ["C++", "Embedded C", "AUTOSAR", "Python", "AI/ML", "MATLAB", "Linux"],
    hiringStatus: true,
    foundedYear: 1990,
    socialLinks: { linkedin: "https://linkedin.com/company/kpit-technologies" },
  },
  {
    name: "Cybage Software",
    slug: "cybage-software",
    description:
      "Cybage is a technology consulting company that provides product engineering, digital solutions, and outsourced product development. Headquartered in Pune with global delivery centers.",
    industry: "IT Services",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Cybage Towers, Survey No. 13A/1+2+3/1, Kalyani Nagar, Pune 411006",
    website: "https://www.cybage.com",
    technologies: ["Java", ".NET", "React", "Angular", "AWS", "Azure", "DevOps"],
    hiringStatus: true,
    foundedYear: 1995,
    socialLinks: { linkedin: "https://linkedin.com/company/cybage" },
  },
  {
    name: "Tata Technologies",
    slug: "tata-technologies",
    description:
      "Tata Technologies is a global engineering and product development digital services company. They help manufacturers design, develop, and deliver better products using digital engineering and manufacturing solutions.",
    industry: "Engineering Services",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 3, Pune 411057",
    website: "https://www.tatatechnologies.com",
    technologies: ["CAD/CAM", "PLM", "IoT", "Digital Twin", "AI/ML", "Cloud", "SAP"],
    hiringStatus: true,
    foundedYear: 1994,
    socialLinks: { linkedin: "https://linkedin.com/company/tata-technologies" },
  },
  {
    name: "Quick Heal Technologies",
    slug: "quick-heal-technologies",
    description:
      "Quick Heal Technologies (now Seqrite) is an Indian cybersecurity company headquartered in Pune. They develop antivirus, endpoint security, and enterprise cybersecurity solutions used by millions globally.",
    industry: "Cybersecurity",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Marvel Edge, Viman Nagar, Pune 411014",
    website: "https://www.quickheal.com",
    technologies: ["C++", "Python", "Machine Learning", "Windows SDK", "Linux", "Android"],
    hiringStatus: true,
    foundedYear: 1993,
    socialLinks: { linkedin: "https://linkedin.com/company/quick-heal-technologies" },
  },
  {
    name: "Xoriant",
    slug: "xoriant",
    description:
      "Xoriant is a Silicon Valley-headquartered digital engineering company with a major development center in Pune. They provide product engineering, cloud, data analytics, and AI/ML services.",
    industry: "IT Services",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Commerzone IT Park, Yerwada, Pune 411006",
    website: "https://www.xoriant.com",
    technologies: ["Java", "Python", "React", "AWS", "Kubernetes", "Spark", "Kafka"],
    hiringStatus: true,
    foundedYear: 1990,
    socialLinks: { linkedin: "https://linkedin.com/company/xoriant" },
  },
  {
    name: "Icertis",
    slug: "icertis",
    description:
      "Icertis is a contract lifecycle management (CLM) platform company headquartered in Pune. Their AI-powered platform manages contracts for Fortune 500 companies, transforming contract management with intelligence.",
    industry: "Enterprise SaaS",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "ICC Trade Tower, Senapati Bapat Road, Pune 411016",
    website: "https://www.icertis.com",
    technologies: ["Azure", ".NET", "React", "AI/ML", "Kubernetes", "Microservices", "TypeScript"],
    hiringStatus: true,
    foundedYear: 2009,
    socialLinks: { linkedin: "https://linkedin.com/company/icertis" },
  },
  {
    name: "Druva",
    slug: "druva",
    description:
      "Druva provides cloud data protection and management. With a significant engineering center in Pune, they offer SaaS-based backup, disaster recovery, and data governance for enterprises.",
    industry: "Cloud / Data Protection",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "ICC Trade Tower, Senapati Bapat Road, Pune 411016",
    website: "https://www.druva.com",
    technologies: ["Go", "Python", "AWS", "React", "Kubernetes", "Terraform", "gRPC"],
    hiringStatus: true,
    foundedYear: 2008,
    socialLinks: { linkedin: "https://linkedin.com/company/druva" },
  },
  {
    name: "PubMatic",
    slug: "pubmatic",
    description:
      "PubMatic is a digital advertising technology company with a major engineering center in Pune. Their sell-side platform helps publishers and app developers maximize their digital ad revenue.",
    industry: "Ad Tech",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Amar Paradigm, Baner Road, Pune 411045",
    website: "https://www.pubmatic.com",
    technologies: ["Java", "Go", "Python", "Kafka", "Hadoop", "React", "AWS"],
    hiringStatus: true,
    foundedYear: 2006,
    socialLinks: { linkedin: "https://linkedin.com/company/pubmatic" },
  },

  // ── Global MNCs with Pune Engineering Centers ─────────────────────
  {
    name: "Barclays Technology Centre",
    slug: "barclays-technology-centre-pune",
    description:
      "Barclays Technology Centre in Pune is one of the largest technology hubs for Barclays globally. Engineers here build core banking platforms, trading systems, risk management, and fintech solutions.",
    industry: "Banking / Fintech",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 3, Pune 411057",
    website: "https://home.barclays/careers",
    technologies: ["Java", "Spring Boot", "React", "Python", "Kafka", "AWS", "Kubernetes"],
    hiringStatus: true,
    foundedYear: 2007,
    socialLinks: { linkedin: "https://linkedin.com/company/barclays" },
  },
  {
    name: "HSBC Technology India",
    slug: "hsbc-technology-pune",
    description:
      "HSBC Technology India's Pune center is a global technology hub building digital banking solutions, cybersecurity systems, and data analytics platforms for HSBC worldwide.",
    industry: "Banking / Fintech",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "EON Free Zone, Kharadi, Pune 411014",
    website: "https://www.hsbc.com/careers",
    technologies: ["Java", "Angular", "Python", "AWS", "Microservices", "Blockchain", "AI/ML"],
    hiringStatus: true,
    foundedYear: 2003,
    socialLinks: { linkedin: "https://linkedin.com/company/hsbc" },
  },
  {
    name: "Deutsche Bank Technology Centre",
    slug: "deutsche-bank-technology-pune",
    description:
      "Deutsche Bank's Pune technology centre builds global trading platforms, risk management systems, and digital banking infrastructure. One of the bank's largest tech hubs globally.",
    industry: "Banking / Fintech",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Commerzone IT Park, Yerwada, Pune 411006",
    website: "https://careers.db.com",
    technologies: ["Java", "Python", "React", "Kubernetes", "Kafka", "Spring Boot", "SQL"],
    hiringStatus: true,
    foundedYear: 2005,
    socialLinks: { linkedin: "https://linkedin.com/company/deutsche-bank" },
  },
  {
    name: "BNY Mellon Technology",
    slug: "bny-mellon-technology-pune",
    description:
      "BNY Mellon's Pune technology center develops asset management platforms, custody and clearing systems, and data analytics solutions for the global financial services company.",
    industry: "Banking / Fintech",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "EON Free Zone, Kharadi, Pune 411014",
    website: "https://www.bnymellon.com/careers",
    technologies: ["Java", "Python", "React", "AWS", "Microservices", ".NET", "Angular"],
    hiringStatus: true,
    foundedYear: 2007,
    socialLinks: { linkedin: "https://linkedin.com/company/bny-mellon" },
  },
  {
    name: "Mastercard Technology",
    slug: "mastercard-technology-pune",
    description:
      "Mastercard's Pune technology hub develops payment processing systems, fraud detection AI, cybersecurity solutions, and fintech innovations for the global payments network.",
    industry: "Payments / Fintech",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Upper Indiranagar, Bibwewadi, Pune 411037",
    website: "https://www.mastercard.com/careers",
    technologies: ["Java", "Scala", "Python", "Kafka", "Spark", "React", "AI/ML"],
    hiringStatus: true,
    foundedYear: 2011,
    socialLinks: { linkedin: "https://linkedin.com/company/mastercard" },
  },
  {
    name: "Nvidia India",
    slug: "nvidia-pune",
    description:
      "Nvidia's Pune office focuses on GPU computing, AI/deep learning research, autonomous vehicle technology, and graphics software development for the global chipmaker.",
    industry: "Semiconductors / AI",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Magarpatta City, Hadapsar, Pune 411028",
    website: "https://www.nvidia.com/careers",
    technologies: ["CUDA", "C++", "Python", "Deep Learning", "TensorRT", "Linux", "GPU Computing"],
    hiringStatus: true,
    foundedYear: 2005,
    socialLinks: { linkedin: "https://linkedin.com/company/nvidia" },
  },
  {
    name: "Siemens Technology",
    slug: "siemens-technology-pune",
    description:
      "Siemens Technology and Services in Pune is a major R&D center developing industrial automation software, IoT platforms, digital twin solutions, and smart infrastructure technology.",
    industry: "Industrial Technology",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 3, Pune 411057",
    website: "https://www.siemens.com/careers",
    technologies: ["C++", "Python", "IoT", "Digital Twin", "NX", "Teamcenter", "Cloud"],
    hiringStatus: true,
    foundedYear: 1995,
    socialLinks: { linkedin: "https://linkedin.com/company/siemens" },
  },
  {
    name: "John Deere Technology Centre",
    slug: "john-deere-technology-pune",
    description:
      "John Deere's India Technology Centre in Pune develops precision agriculture software, autonomous farming solutions, telematics, and IoT platforms for the global agricultural equipment company.",
    industry: "AgriTech / IoT",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Magarpatta City, Hadapsar, Pune 411028",
    website: "https://www.deere.com/careers",
    technologies: ["Java", "Python", "IoT", "AWS", "React", "Machine Learning", "Embedded C"],
    hiringStatus: true,
    foundedYear: 2001,
    socialLinks: { linkedin: "https://linkedin.com/company/john-deere" },
  },
  {
    name: "Emerson Innovation Center",
    slug: "emerson-innovation-center-pune",
    description:
      "Emerson's Innovation Center in Pune develops industrial automation, process control systems, and IoT-enabled solutions for manufacturing, energy, and life sciences industries.",
    industry: "Industrial Automation",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 3, Pune 411057",
    website: "https://www.emerson.com/careers",
    technologies: ["C++", "Embedded C", "Python", "IoT", "SCADA", ".NET", "Azure"],
    hiringStatus: true,
    foundedYear: 2003,
    socialLinks: { linkedin: "https://linkedin.com/company/emerson" },
  },
  {
    name: "Veritas Technologies",
    slug: "veritas-technologies-pune",
    description:
      "Veritas Technologies' Pune center develops enterprise data management, backup and recovery, and multi-cloud data services. Pune is one of their largest engineering hubs globally.",
    industry: "Data Management",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Magarpatta City, Hadapsar, Pune 411028",
    website: "https://www.veritas.com/careers",
    technologies: ["C++", "Java", "Python", "Kubernetes", "AWS", "Linux", "Go"],
    hiringStatus: true,
    foundedYear: 2005,
    socialLinks: { linkedin: "https://linkedin.com/company/veritas-technologies" },
  },
  {
    name: "Amdocs",
    slug: "amdocs-pune",
    description:
      "Amdocs' Pune development center builds telecom OSS/BSS solutions, digital experience platforms, and 5G-ready systems for communications service providers globally.",
    industry: "Telecom Software",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 2, Pune 411057",
    website: "https://www.amdocs.com/careers",
    technologies: ["Java", "React", "Microservices", "Kubernetes", "Oracle", "AWS", "5G"],
    hiringStatus: true,
    foundedYear: 2002,
    socialLinks: { linkedin: "https://linkedin.com/company/amdocs" },
  },
  {
    name: "BMC Software",
    slug: "bmc-software-pune",
    description:
      "BMC Software's Pune office develops IT service management, AIOps, and DevOps solutions. Their Helix platform helps enterprises manage and automate IT operations at scale.",
    industry: "Enterprise Software",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "EON Free Zone, Kharadi, Pune 411014",
    website: "https://www.bmc.com/careers",
    technologies: ["Java", "React", "Python", "Kubernetes", "AI/ML", "Docker", "Go"],
    hiringStatus: true,
    foundedYear: 2004,
    socialLinks: { linkedin: "https://linkedin.com/company/bmc-software" },
  },
  {
    name: "Synechron",
    slug: "synechron-pune",
    description:
      "Synechron is a global digital transformation consulting firm with a major center in Pune. They specialize in financial services technology, blockchain, AI, and cloud solutions.",
    industry: "Fintech Consulting",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 1, Pune 411057",
    website: "https://www.synechron.com",
    technologies: ["Java", "React", "Blockchain", "AI/ML", "AWS", "Azure", "Spring Boot"],
    hiringStatus: true,
    foundedYear: 2001,
    socialLinks: { linkedin: "https://linkedin.com/company/synechron" },
  },
  {
    name: "Fiserv India",
    slug: "fiserv-pune",
    description:
      "Fiserv's Pune technology center builds payment processing, core banking, and digital commerce solutions for financial institutions and merchants worldwide.",
    industry: "Payments / Fintech",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 1, Pune 411057",
    website: "https://www.fiserv.com/careers",
    technologies: ["Java", ".NET", "React", "Kubernetes", "AWS", "SQL Server", "Kafka"],
    hiringStatus: true,
    foundedYear: 2006,
    socialLinks: { linkedin: "https://linkedin.com/company/fiserv" },
  },
  {
    name: "Cvent India",
    slug: "cvent-pune",
    description:
      "Cvent's Pune engineering center develops event management technology, venue sourcing platforms, and marketing automation tools for the global events industry.",
    industry: "Event Tech / SaaS",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Magarpatta City, Hadapsar, Pune 411028",
    website: "https://www.cvent.com/careers",
    technologies: ["Java", "React", "AWS", "Elasticsearch", "Python", "Microservices", "GraphQL"],
    hiringStatus: true,
    foundedYear: 2010,
    socialLinks: { linkedin: "https://linkedin.com/company/cvent" },
  },

  // ── Product Companies & Startups ──────────────────────────────────
  {
    name: "PhonePe",
    slug: "phonepe-pune",
    description:
      "PhonePe is India's leading digital payments platform with a significant engineering presence in Pune. They power UPI payments, mutual fund investments, insurance, and digital commerce for hundreds of millions of users.",
    industry: "Fintech / Payments",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Salarpuria Softzone, Hinjewadi Phase 1, Pune 411057",
    website: "https://www.phonepe.com/careers",
    technologies: ["Java", "Kotlin", "React", "Flutter", "Kafka", "Kubernetes", "Go"],
    hiringStatus: true,
    foundedYear: 2015,
    socialLinks: { linkedin: "https://linkedin.com/company/phonepe" },
  },
  {
    name: "GlobalLogic",
    slug: "globallogic-pune",
    description:
      "GlobalLogic (a Hitachi Group Company) is a digital engineering company with a Pune development center. They build software products for healthcare, automotive, communications, and media companies.",
    industry: "Digital Engineering",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Kalyani Nagar, Pune 411006",
    website: "https://www.globallogic.com/careers",
    technologies: ["Java", "React", "Angular", "Python", "AWS", "IoT", "Embedded C"],
    hiringStatus: true,
    foundedYear: 2006,
    socialLinks: { linkedin: "https://linkedin.com/company/globallogic" },
  },
  {
    name: "ThoughtWorks",
    slug: "thoughtworks-pune",
    description:
      "ThoughtWorks is a global technology consultancy with a Pune office. Known for agile practices, open source contributions, and building custom software for digital transformation.",
    industry: "Technology Consulting",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Baner Road, Pune 411045",
    website: "https://www.thoughtworks.com/careers",
    technologies: ["Java", "Go", "React", "Python", "Kubernetes", "AWS", "Terraform"],
    hiringStatus: true,
    foundedYear: 2005,
    socialLinks: { linkedin: "https://linkedin.com/company/thoughtworks" },
  },
  {
    name: "Harman Connected Services",
    slug: "harman-connected-services-pune",
    description:
      "Harman Connected Services (a Samsung company) in Pune develops connected car platforms, IoT solutions, and enterprise cloud services for automotive and consumer electronics.",
    industry: "Connected Devices / IoT",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 1, Pune 411057",
    website: "https://www.harman.com/careers",
    technologies: ["Java", "C++", "Embedded C", "Android", "IoT", "AWS", "Python"],
    hiringStatus: true,
    foundedYear: 2004,
    socialLinks: { linkedin: "https://linkedin.com/company/harman-connected-services" },
  },
  {
    name: "Forcepoint",
    slug: "forcepoint-pune",
    description:
      "Forcepoint's Pune R&D center develops cybersecurity solutions including data loss prevention, cloud security, and insider threat protection for enterprises and government agencies.",
    industry: "Cybersecurity",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "EON Free Zone, Kharadi, Pune 411014",
    website: "https://www.forcepoint.com/careers",
    technologies: ["C++", "Python", "Go", "React", "AWS", "Machine Learning", "Linux"],
    hiringStatus: true,
    foundedYear: 2008,
    socialLinks: { linkedin: "https://linkedin.com/company/forcepoint" },
  },
  {
    name: "Mphasis",
    slug: "mphasis-pune",
    description:
      "Mphasis is a global IT services company applying next-gen technology to help enterprises transform businesses. Their Pune center focuses on cloud, cognitive computing, and digital applications.",
    industry: "IT Services",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 2, Pune 411057",
    website: "https://www.mphasis.com/careers",
    technologies: ["Java", "Python", "AWS", "Azure", "React", "AI/ML", "Salesforce"],
    hiringStatus: true,
    foundedYear: 2003,
    socialLinks: { linkedin: "https://linkedin.com/company/mphasis" },
  },
  {
    name: "Bajaj Finserv Technology",
    slug: "bajaj-finserv-technology",
    description:
      "Bajaj Finserv's technology division in Pune builds digital lending platforms, insurance tech solutions, and fintech products. They power one of India's largest NBFCs with modern technology.",
    industry: "Fintech / BFSI",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Akurdi, Pune 411035",
    website: "https://www.bajajfinserv.in/careers",
    technologies: ["Java", "Spring Boot", "React", "AWS", "Kafka", "Microservices", "Python"],
    hiringStatus: true,
    foundedYear: 2007,
    socialLinks: { linkedin: "https://linkedin.com/company/bajaj-finserv" },
  },
  {
    name: "Tieto (TietoEVRY)",
    slug: "tietoevry-pune",
    description:
      "TietoEVRY's Pune center develops cloud-native enterprise solutions, data-driven services, and digital consulting for Nordic and global enterprises.",
    industry: "IT Services",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 2, Pune 411057",
    website: "https://www.tietoevry.com/careers",
    technologies: ["Java", "Azure", "React", "Python", "Kubernetes", ".NET", "DevOps"],
    hiringStatus: true,
    foundedYear: 2005,
    socialLinks: { linkedin: "https://linkedin.com/company/tietoevry" },
  },
  {
    name: "Searce",
    slug: "searce-pune",
    description:
      "Searce is a niche cloud-first technology consulting company headquartered in Pune. They are a premier Google Cloud partner specializing in cloud migration, data analytics, and AI/ML.",
    industry: "Cloud Consulting",
    size: "MEDIUM" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Baner, Pune 411045",
    website: "https://www.searce.com",
    technologies: ["Google Cloud", "Terraform", "Python", "Go", "BigQuery", "Kubernetes", "React"],
    hiringStatus: true,
    foundedYear: 2004,
    socialLinks: { linkedin: "https://linkedin.com/company/searce" },
  },
  {
    name: "Seclore",
    slug: "seclore-pune",
    description:
      "Seclore is a data-centric security company with a development center in Pune. They provide enterprise rights management and data classification solutions protecting sensitive information.",
    industry: "Cybersecurity",
    size: "MEDIUM" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Baner Road, Pune 411045",
    website: "https://www.seclore.com",
    technologies: ["Java", "C++", ".NET", "React", "AWS", "Cryptography", "Python"],
    hiringStatus: true,
    foundedYear: 2005,
    socialLinks: { linkedin: "https://linkedin.com/company/seclore" },
  },
  {
    name: "Cummins Technology India",
    slug: "cummins-technology-pune",
    description:
      "Cummins India Technical Centre in Pune is a major R&D hub developing power solutions, engine management software, and connected diagnostics for the global engine manufacturer.",
    industry: "Industrial / Engineering",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Balewadi, Pune 411045",
    website: "https://www.cummins.com/careers",
    technologies: ["MATLAB", "Embedded C", "Python", "IoT", "Azure", "Data Analytics", "CAD"],
    hiringStatus: true,
    foundedYear: 2003,
    socialLinks: { linkedin: "https://linkedin.com/company/cummins" },
  },
  {
    name: "eQ Technologic",
    slug: "eq-technologic-pune",
    description:
      "eQ Technologic is a Pune-headquartered product company building model-based systems engineering and digital thread solutions for aerospace, defense, and manufacturing enterprises.",
    industry: "Enterprise Software",
    size: "MEDIUM" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 1, Pune 411057",
    website: "https://www.1702digital.com",
    technologies: ["Java", "React", "GraphQL", "AWS", "PostgreSQL", "Kubernetes", "Python"],
    hiringStatus: true,
    foundedYear: 2000,
    socialLinks: { linkedin: "https://linkedin.com/company/eq-technologic" },
  },

  // ── Large IT Services (Pune offices) ──────────────────────────────
  {
    name: "Infosys Pune",
    slug: "infosys-pune",
    description:
      "Infosys' Pune Development Centre is one of its largest campuses in India. The center houses engineering teams working on digital services, cloud migration, AI solutions, and enterprise software for global clients.",
    industry: "IT Services",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Rajiv Gandhi Infotech Park, Hinjewadi Phase 1, Pune 411057",
    website: "https://www.infosys.com/careers",
    technologies: ["Java", "Python", "React", "Angular", "AWS", "Azure", "SAP"],
    hiringStatus: true,
    foundedYear: 1999,
    socialLinks: { linkedin: "https://linkedin.com/company/infosys" },
  },
  {
    name: "TCS Pune",
    slug: "tcs-pune",
    description:
      "TCS (Tata Consultancy Services) Pune campus houses thousands of engineers working on digital transformation, cloud, IoT, and AI solutions for global enterprises across all major industries.",
    industry: "IT Services",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Rajiv Gandhi Infotech Park, Hinjewadi Phase 3, Pune 411057",
    website: "https://www.tcs.com/careers",
    technologies: ["Java", ".NET", "Python", "AWS", "Azure", "SAP", "AI/ML"],
    hiringStatus: true,
    foundedYear: 1999,
    socialLinks: { linkedin: "https://linkedin.com/company/tata-consultancy-services" },
  },
  {
    name: "Wipro Pune",
    slug: "wipro-pune",
    description:
      "Wipro's Pune development center delivers IT services, consulting, and digital solutions. Teams here work on cloud transformation, cybersecurity, enterprise applications, and engineering services.",
    industry: "IT Services",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 3, Pune 411057",
    website: "https://careers.wipro.com",
    technologies: ["Java", "Python", "Angular", "AWS", "Azure", "SAP", "Salesforce"],
    hiringStatus: true,
    foundedYear: 2001,
    socialLinks: { linkedin: "https://linkedin.com/company/wipro" },
  },
  {
    name: "Cognizant Pune",
    slug: "cognizant-pune",
    description:
      "Cognizant's Pune center is a major delivery hub for digital engineering, cloud services, and IT consulting. They serve clients across banking, healthcare, and manufacturing sectors.",
    industry: "IT Services",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 2, Pune 411057",
    website: "https://careers.cognizant.com",
    technologies: ["Java", ".NET", "React", "AWS", "Azure", "Pega", "Salesforce"],
    hiringStatus: true,
    foundedYear: 2002,
    socialLinks: { linkedin: "https://linkedin.com/company/cognizant" },
  },
  {
    name: "Tech Mahindra Pune",
    slug: "tech-mahindra-pune",
    description:
      "Tech Mahindra's Pune campus focuses on telecom solutions, enterprise digital transformation, and 5G technology services for global communications and enterprise clients.",
    industry: "IT Services / Telecom",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Rajiv Gandhi Infotech Park, Hinjewadi Phase 3, Pune 411057",
    website: "https://careers.techmahindra.com",
    technologies: ["Java", "5G", "AI/ML", "Azure", "React", "Node.js", "Blockchain"],
    hiringStatus: true,
    foundedYear: 2003,
    socialLinks: { linkedin: "https://linkedin.com/company/tech-mahindra" },
  },

  // ── Mid-size & Growing Companies ──────────────────────────────────
  {
    name: "Harbinger Group",
    slug: "harbinger-group-pune",
    description:
      "Harbinger Group is a Pune-based product engineering company specializing in eLearning, HRTech, and SaaS product development. They build platforms for education and workforce management.",
    industry: "EdTech / HRTech",
    size: "MEDIUM" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Baner Road, Pune 411045",
    website: "https://www.harbingergroup.com",
    technologies: ["React", "Node.js", "Python", "AWS", ".NET", "Angular", "AI/ML"],
    hiringStatus: true,
    foundedYear: 1990,
    socialLinks: { linkedin: "https://linkedin.com/company/harbinger-group" },
  },
  {
    name: "Calsoft",
    slug: "calsoft-pune",
    description:
      "Calsoft is a Pune-headquartered product engineering company specializing in storage, virtualization, cloud, and networking solutions for ISVs and technology companies.",
    industry: "Product Engineering",
    size: "MEDIUM" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Baner, Pune 411045",
    website: "https://www.calsoftinc.com",
    technologies: ["C++", "Python", "Linux", "OpenStack", "Docker", "Kubernetes", "Go"],
    hiringStatus: true,
    foundedYear: 1998,
    socialLinks: { linkedin: "https://linkedin.com/company/calsoft" },
  },
  {
    name: "Accenture Pune",
    slug: "accenture-pune",
    description:
      "Accenture's Pune Advanced Technology Center delivers consulting, technology, and outsourcing services. Teams work on cloud migration, SAP implementations, AI solutions, and industry-specific digital platforms.",
    industry: "IT Consulting",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 2, Pune 411057",
    website: "https://www.accenture.com/careers",
    technologies: ["Java", "SAP", "AWS", "Azure", "React", "Salesforce", "AI/ML"],
    hiringStatus: true,
    foundedYear: 2001,
    socialLinks: { linkedin: "https://linkedin.com/company/accenture" },
  },
  {
    name: "Atos India",
    slug: "atos-pune",
    description:
      "Atos (formerly Syntel) Pune center delivers digital transformation, cybersecurity, and decarbonization technology solutions for enterprise clients across banking, healthcare, and manufacturing.",
    industry: "IT Services",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 1, Pune 411057",
    website: "https://atos.net/en/careers",
    technologies: ["Java", ".NET", "SAP", "Cloud", "Cybersecurity", "IoT", "AI"],
    hiringStatus: true,
    foundedYear: 2002,
    socialLinks: { linkedin: "https://linkedin.com/company/atos" },
  },
  {
    name: "Priceline (Booking Holdings)",
    slug: "priceline-pune",
    description:
      "Priceline's Pune technology center develops travel booking platforms, pricing algorithms, and search optimization systems for one of the world's largest online travel companies.",
    industry: "Travel Tech",
    size: "LARGE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Kalyani Nagar, Pune 411006",
    website: "https://www.priceline.com/careers",
    technologies: ["Java", "Kotlin", "React", "AWS", "Kafka", "Elasticsearch", "Python"],
    hiringStatus: true,
    foundedYear: 2015,
    socialLinks: { linkedin: "https://linkedin.com/company/priceline-com" },
  },
  {
    name: "LTIMindtree Pune",
    slug: "ltimindtree-pune",
    description:
      "LTIMindtree's Pune campus is a key delivery center for digital engineering, cloud, data analytics, and enterprise IT services across banking, insurance, and manufacturing.",
    industry: "IT Services",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 3, Pune 411057",
    website: "https://www.ltimindtree.com/careers",
    technologies: ["Java", "Python", "AWS", "Azure", "React", "SAP", "Snowflake"],
    hiringStatus: true,
    foundedYear: 2002,
    socialLinks: { linkedin: "https://linkedin.com/company/ltimindtree" },
  },
  {
    name: "Capgemini Pune",
    slug: "capgemini-pune",
    description:
      "Capgemini's Pune center delivers consulting, technology, and digital transformation services. Teams focus on cloud engineering, intelligent industry solutions, and enterprise management.",
    industry: "IT Consulting",
    size: "ENTERPRISE" as const,
    city: "Pune",
    state: "Maharashtra",
    address: "Talawade IT Park, Pune 411062",
    website: "https://www.capgemini.com/careers",
    technologies: ["Java", "SAP", "Salesforce", "AWS", "Azure", "PEGA", "React"],
    hiringStatus: true,
    foundedYear: 2002,
    socialLinks: { linkedin: "https://linkedin.com/company/capgemini" },
  },
];

async function seedPuneCompanies() {
  console.log("Seeding Pune tech companies...\n");

  // Get or create admin user
  let admin = await prisma.user.findFirst({ where: { role: "ADMIN" } });
  if (!admin) {
    admin = await prisma.user.upsert({
      where: { email: "admin@internhack.com" },
      update: {},
      create: {
        name: "Admin User",
        email: "admin@internhack.com",
        password: "$2a$10$EqHuL3qAJkLk6qvXkZzGxeJ5N5k7f7/Z2k3a5w1Q9Hj7KjzXMRWHi",
        role: "ADMIN",
      },
    });
  }

  let created = 0;
  let skipped = 0;

  for (const companyData of puneCompanies) {
    const existing = await prisma.company.findUnique({
      where: { slug: companyData.slug },
    });

    if (existing) {
      console.log(`  SKIP: ${companyData.name} (already exists)`);
      skipped++;
      continue;
    }

    await prisma.company.create({
      data: {
        name: companyData.name,
        slug: companyData.slug,
        description: companyData.description,
        industry: companyData.industry,
        size: companyData.size,
        city: companyData.city,
        state: companyData.state,
        address: companyData.address,
        website: companyData.website,
        technologies: companyData.technologies,
        hiringStatus: companyData.hiringStatus,
        foundedYear: companyData.foundedYear,
        socialLinks: companyData.socialLinks,
        isApproved: true,
        createdById: admin.id,
      },
    });

    console.log(`  ADDED: ${companyData.name}`);
    created++;
  }

  console.log(`\nDone! Created: ${created}, Skipped: ${skipped}, Total Pune companies: ${puneCompanies.length}`);
}

seedPuneCompanies()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
