import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const connectionString = process.env["DATABASE_URL"] ?? "";
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

interface Q {
  question: string;
  optionA: string; optionB: string; optionC: string; optionD: string;
  correctAnswer: string; explanation: string; difficulty: string; companies: string[];
}

const TOPICS: Record<number, Q[]> = {
  // ── Fill in the Blanks (id=81) ──
  81: [
    { question: "The teacher asked the students to _____ the experiment carefully before drawing conclusions.", optionA: "observe", optionB: "ignore", optionC: "neglect", optionD: "avoid", correctAnswer: "A", explanation: "The context of an experiment requires careful observation before conclusions.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "Despite his _____ efforts, he could not finish the project on time.", optionA: "half-hearted", optionB: "tireless", optionC: "minimal", optionD: "lazy", correctAnswer: "B", explanation: "'Despite' indicates contrast — he worked tirelessly yet couldn't finish, showing it was difficult.", difficulty: "EASY", companies: ["TCS", "Wipro"] },
    { question: "The _____ of the mountain was so steep that only experienced climbers attempted it.", optionA: "base", optionB: "ascent", optionC: "height", optionD: "valley", correctAnswer: "B", explanation: "The 'ascent' (climb) being steep makes experienced climbers the only ones to attempt it.", difficulty: "MEDIUM", companies: ["Accenture", "Cognizant"] },
    { question: "She was so _____ that she could convince anyone with her arguments.", optionA: "timid", optionB: "eloquent", optionC: "silent", optionD: "confused", correctAnswer: "B", explanation: "Eloquent means fluent and persuasive in speaking, fitting the context of convincing others.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "The new policy will _____ into effect from next month.", optionA: "come", optionB: "go", optionC: "run", optionD: "fall", correctAnswer: "A", explanation: "'Come into effect' is the correct idiomatic expression for a policy becoming active.", difficulty: "EASY", companies: ["Wipro", "Cognizant"] },
    { question: "His _____ behaviour at the party embarrassed everyone present.", optionA: "polite", optionB: "graceful", optionC: "boorish", optionD: "charming", correctAnswer: "C", explanation: "Boorish means rude and ill-mannered, which would cause embarrassment.", difficulty: "MEDIUM", companies: ["TCS", "Accenture"] },
    { question: "The government has decided to _____ the old bridge and build a new one.", optionA: "construct", optionB: "demolish", optionC: "paint", optionD: "admire", correctAnswer: "B", explanation: "To replace with a new one, the old bridge must be demolished (torn down).", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "The scientist's _____ research led to a breakthrough in cancer treatment.", optionA: "groundbreaking", optionB: "mundane", optionC: "ordinary", optionD: "trivial", correctAnswer: "A", explanation: "Groundbreaking research is innovative and leads to breakthroughs.", difficulty: "EASY", companies: ["Wipro", "Cognizant"] },
    { question: "We must _____ our natural resources for future generations.", optionA: "exploit", optionB: "waste", optionC: "conserve", optionD: "destroy", correctAnswer: "C", explanation: "Conserving natural resources means protecting them for future use.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
    { question: "The manager was _____ about the team's chances of winning the contract.", optionA: "pessimistic", optionB: "optimistic", optionC: "indifferent", optionD: "unaware", correctAnswer: "B", explanation: "Being optimistic means having a positive outlook about winning the contract.", difficulty: "EASY", companies: ["Infosys", "Cognizant"] },
    { question: "The _____ between the two countries has been going on for decades.", optionA: "friendship", optionB: "alliance", optionC: "conflict", optionD: "harmony", correctAnswer: "C", explanation: "A conflict going on for decades implies a long-standing dispute.", difficulty: "EASY", companies: ["TCS", "Wipro"] },
    { question: "Her _____ knowledge of the subject impressed the interview panel.", optionA: "superficial", optionB: "comprehensive", optionC: "limited", optionD: "negligible", correctAnswer: "B", explanation: "Comprehensive knowledge (thorough and complete) would impress an interview panel.", difficulty: "EASY", companies: ["Accenture", "Cognizant"] },
    { question: "The CEO _____ his resignation after the company reported massive losses.", optionA: "withdrew", optionB: "tendered", optionC: "denied", optionD: "postponed", correctAnswer: "B", explanation: "'Tendered his resignation' is the correct phrase meaning formally submitted.", difficulty: "MEDIUM", companies: ["TCS", "Infosys"] },
    { question: "It is _____ to judge a person by their appearance alone.", optionA: "wise", optionB: "prudent", optionC: "unwise", optionD: "necessary", correctAnswer: "C", explanation: "It is unwise (foolish) to judge someone solely based on appearance.", difficulty: "EASY", companies: ["Wipro", "Cognizant"] },
    { question: "The detective's _____ eye noticed every small detail at the crime scene.", optionA: "blind", optionB: "keen", optionC: "weak", optionD: "dull", correctAnswer: "B", explanation: "A keen eye means sharp and observant, essential for a detective.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
  ],

  // ── Direct and Indirect Speech (id=84) ──
  84: [
    { question: "He said, 'I am going to the market.' Change to indirect speech.", optionA: "He said that he was going to the market.", optionB: "He said that I am going to the market.", optionC: "He said that he is going to the market.", optionD: "He told that he was going to the market.", correctAnswer: "A", explanation: "In indirect speech: 'I' → 'he', 'am going' → 'was going'. Reporting verb 'said' doesn't need an object before 'that'.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "She said to me, 'Where do you live?' Change to indirect speech.", optionA: "She asked me where I lived.", optionB: "She asked me where do I live.", optionC: "She told me where I lived.", optionD: "She said to me where I live.", correctAnswer: "A", explanation: "Indirect: 'said to me' → 'asked me', question becomes statement word order, 'you' → 'I', 'live' → 'lived'.", difficulty: "EASY", companies: ["TCS", "Wipro"] },
    { question: "The teacher said, 'The earth revolves around the sun.' Change to indirect speech.", optionA: "The teacher said that the earth revolved around the sun.", optionB: "The teacher said that the earth revolves around the sun.", optionC: "The teacher told that earth is revolving around the sun.", optionD: "The teacher said the earth has revolved around the sun.", correctAnswer: "B", explanation: "Universal truths remain in present tense even in indirect speech.", difficulty: "MEDIUM", companies: ["Accenture", "Cognizant"] },
    { question: "He said to her, 'Please help me.' Change to indirect speech.", optionA: "He requested her to help him.", optionB: "He said her to please help him.", optionC: "He told her to please help me.", optionD: "He ordered her to help him.", correctAnswer: "A", explanation: "'Please' indicates a request. Indirect: 'said to her' → 'requested her', 'help me' → 'to help him'.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "She asked me where I had been. Change to direct speech.", optionA: "She said to me, 'Where have you been?'", optionB: "She said to me, 'Where had you been?'", optionC: "She told me, 'Where were you?'", optionD: "She asked me, 'Where you had been?'", correctAnswer: "A", explanation: "Indirect 'had been' → Direct 'have you been'. 'Asked me' → 'said to me' with question mark.", difficulty: "MEDIUM", companies: ["Wipro", "Cognizant"] },
    { question: "'Don't touch the wire,' said the electrician. Change to indirect speech.", optionA: "The electrician warned not to touch the wire.", optionB: "The electrician said don't touch the wire.", optionC: "The electrician told not touch the wire.", optionD: "The electrician warned to not touch the wire.", correctAnswer: "A", explanation: "Negative imperative with warning context: 'warned not to touch the wire'.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
    { question: "He said, 'I will go tomorrow.' Change to indirect speech.", optionA: "He said that he would go the next day.", optionB: "He said that he will go tomorrow.", optionC: "He said he would go tomorrow.", optionD: "He told that he will go the next day.", correctAnswer: "A", explanation: "'will' → 'would', 'tomorrow' → 'the next day', 'I' → 'he'.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "She said, 'I have been working since morning.' Change to indirect speech.", optionA: "She said that she had been working since morning.", optionB: "She said that she has been working since morning.", optionC: "She told that she had been working since morning.", optionD: "She said she is working since morning.", correctAnswer: "A", explanation: "'have been working' → 'had been working'. Present perfect continuous → past perfect continuous.", difficulty: "MEDIUM", companies: ["Wipro", "Cognizant"] },
    { question: "The mother said to the child, 'Do not go out in the rain.' Change to indirect speech.", optionA: "The mother told the child not to go out in the rain.", optionB: "The mother said to the child not go out in the rain.", optionC: "The mother forbade the child to go in rain.", optionD: "The mother ordered the child don't go in the rain.", correctAnswer: "A", explanation: "'said to' + imperative → 'told ... (not) to'. 'Do not go' → 'not to go'.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
    { question: "He said, 'Alas! I have lost my wallet.' Change to indirect speech.", optionA: "He exclaimed with sorrow that he had lost his wallet.", optionB: "He said alas that he has lost his wallet.", optionC: "He told that he had lost his wallet sadly.", optionD: "He exclaimed that he lost his wallet.", correctAnswer: "A", explanation: "'Alas!' expresses sorrow → 'exclaimed with sorrow'. 'have lost' → 'had lost'.", difficulty: "MEDIUM", companies: ["Infosys", "Cognizant"] },
    { question: "Ram said to Shyam, 'Did you attend the meeting yesterday?' Change to indirect speech.", optionA: "Ram asked Shyam if he had attended the meeting the previous day.", optionB: "Ram asked Shyam did he attend the meeting yesterday.", optionC: "Ram told Shyam whether he attended the meeting.", optionD: "Ram said to Shyam had he attended the meeting.", correctAnswer: "A", explanation: "Yes/no question: 'Did you' → 'if/whether he had'. 'yesterday' → 'the previous day'.", difficulty: "MEDIUM", companies: ["TCS", "Wipro"] },
    { question: "She said, 'How beautiful the sunset is!' Change to indirect speech.", optionA: "She exclaimed that the sunset was very beautiful.", optionB: "She said how beautiful the sunset is.", optionC: "She told that sunset is beautiful.", optionD: "She exclaimed the sunset was how beautiful.", correctAnswer: "A", explanation: "Exclamatory sentence: 'How beautiful!' → 'exclaimed that ... was very beautiful'.", difficulty: "EASY", companies: ["Accenture", "Cognizant"] },
    { question: "The captain said, 'Let us start the game.' Change to indirect speech.", optionA: "The captain suggested starting the game.", optionB: "The captain said let us start the game.", optionC: "The captain told to start the game.", optionD: "The captain ordered us to start the game.", correctAnswer: "A", explanation: "'Let us' suggests a proposal → 'suggested starting' or 'suggested that they start'.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "He told me that he had been waiting for an hour. Change to direct speech.", optionA: "He said to me, 'I have been waiting for an hour.'", optionB: "He said, 'I had been waiting for an hour.'", optionC: "He told me, 'I was waiting for an hour.'", optionD: "He said to me, 'I am waiting for an hour.'", correctAnswer: "A", explanation: "'had been waiting' in indirect → 'have been waiting' in direct. 'told me' → 'said to me'.", difficulty: "MEDIUM", companies: ["Wipro", "Cognizant"] },
    { question: "'Sit down,' said the teacher to the students. Change to indirect speech.", optionA: "The teacher ordered the students to sit down.", optionB: "The teacher said students sit down.", optionC: "The teacher told sit down to students.", optionD: "The teacher requested to sit down.", correctAnswer: "A", explanation: "Teacher giving instruction = command → 'ordered the students to sit down'.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
  ],

  // ── One Word Substitution (id=76) ──
  76: [
    { question: "A person who loves books is called:", optionA: "Bibliophile", optionB: "Philanthropist", optionC: "Misanthrope", optionD: "Bibliophobe", correctAnswer: "A", explanation: "Bibliophile = biblio (book) + phile (lover). A person who loves and collects books.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "One who can speak two languages fluently:", optionA: "Polyglot", optionB: "Bilingual", optionC: "Linguist", optionD: "Monolingual", correctAnswer: "B", explanation: "Bilingual means able to speak two languages. Polyglot means multiple languages.", difficulty: "EASY", companies: ["TCS", "Wipro"] },
    { question: "A government ruled by a king or queen:", optionA: "Democracy", optionB: "Monarchy", optionC: "Aristocracy", optionD: "Theocracy", correctAnswer: "B", explanation: "Monarchy = government headed by a monarch (king/queen).", difficulty: "EASY", companies: ["Accenture", "Cognizant"] },
    { question: "A person who cannot read or write:", optionA: "Literate", optionB: "Scholar", optionC: "Illiterate", optionD: "Numerate", correctAnswer: "C", explanation: "Illiterate = unable to read or write.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "Killing of one's own brother:", optionA: "Homicide", optionB: "Fratricide", optionC: "Patricide", optionD: "Regicide", correctAnswer: "B", explanation: "Fratricide = killing one's brother. Patricide = father. Regicide = king.", difficulty: "MEDIUM", companies: ["Wipro", "Cognizant"] },
    { question: "A person who eats human flesh:", optionA: "Herbivore", optionB: "Omnivore", optionC: "Carnivore", optionD: "Cannibal", correctAnswer: "D", explanation: "A cannibal is a person who eats human flesh.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
    { question: "A place where birds are kept:", optionA: "Apiary", optionB: "Aviary", optionC: "Kennel", optionD: "Aquarium", correctAnswer: "B", explanation: "Aviary = enclosure for birds. Apiary = for bees. Kennel = for dogs.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "One who looks at the bright side of things:", optionA: "Pessimist", optionB: "Optimist", optionC: "Cynic", optionD: "Skeptic", correctAnswer: "B", explanation: "An optimist sees the positive/bright side of situations.", difficulty: "EASY", companies: ["Wipro", "Cognizant"] },
    { question: "A person appointed to settle disputes between two parties:", optionA: "Judge", optionB: "Arbitrator", optionC: "Lawyer", optionD: "Prosecutor", correctAnswer: "B", explanation: "An arbitrator is appointed to resolve disputes outside of court.", difficulty: "MEDIUM", companies: ["TCS", "Accenture"] },
    { question: "Something that can be easily broken:", optionA: "Flexible", optionB: "Fragile", optionC: "Resilient", optionD: "Durable", correctAnswer: "B", explanation: "Fragile means easily broken or damaged.", difficulty: "EASY", companies: ["Infosys", "Cognizant"] },
    { question: "A speech delivered without prior preparation:", optionA: "Rehearsed", optionB: "Extempore", optionC: "Scripted", optionD: "Memorized", correctAnswer: "B", explanation: "Extempore (or extemporaneous) means spoken without preparation.", difficulty: "EASY", companies: ["TCS", "Wipro"] },
    { question: "One who walks in sleep:", optionA: "Insomniac", optionB: "Somnambulist", optionC: "Fatalist", optionD: "Egoist", correctAnswer: "B", explanation: "Somnambulist = somn (sleep) + ambul (walk). A sleepwalker.", difficulty: "MEDIUM", companies: ["Accenture", "Cognizant"] },
    { question: "A disease that spreads over a large area:", optionA: "Endemic", optionB: "Epidemic", optionC: "Chronic", optionD: "Acute", correctAnswer: "B", explanation: "Epidemic = a disease affecting many people in an area. Endemic = regularly found in a region.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "A person who is against the established beliefs (especially religion):", optionA: "Atheist", optionB: "Heretic", optionC: "Believer", optionD: "Agnostic", correctAnswer: "B", explanation: "A heretic holds opinions contrary to established (especially religious) beliefs.", difficulty: "MEDIUM", companies: ["Wipro", "Cognizant"] },
    { question: "Writing that cannot be read:", optionA: "Eligible", optionB: "Illegible", optionC: "Invisible", optionD: "Indelible", correctAnswer: "B", explanation: "Illegible = too unclear or badly written to be read. Indelible = cannot be erased.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
  ],

  // ── Paragraph Formation (id=74) — needs 10 more (has 5) ──
  74: [
    { question: "Arrange the sentences to form a coherent paragraph:\nP. It is the largest democracy in the world.\nQ. India is a country in South Asia.\nR. It has a population of over 1.4 billion people.\nS. The country gained independence in 1947.", optionA: "QSRP", optionB: "QPRS", optionC: "QRPS", optionD: "SQRP", correctAnswer: "B", explanation: "Introduction (Q) → key fact about democracy (P) → population detail (R) → historical context (S). QPRS flows logically.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "Arrange the sentences:\nP. However, it requires consistent practice.\nQ. Reading improves vocabulary significantly.\nR. Many students neglect this habit.\nS. Therefore, teachers must encourage daily reading.", optionA: "QPRS", optionB: "RQPS", optionC: "QRPS", optionD: "PQRS", correctAnswer: "A", explanation: "Statement (Q) → caveat (P) → problem (R) → solution (S). QPRS is logical.", difficulty: "EASY", companies: ["TCS", "Wipro"] },
    { question: "Arrange the sentences:\nP. This pollution has serious health consequences.\nQ. Factories release harmful chemicals into rivers.\nR. The government has introduced strict regulations.\nS. Despite this, many factories continue to violate norms.", optionA: "QPRS", optionB: "PQRS", optionC: "QRPS", optionD: "RSPQ", correctAnswer: "A", explanation: "Cause (Q) → effect (P) → response (R) → reality (S). QPRS.", difficulty: "MEDIUM", companies: ["Accenture", "Cognizant"] },
    { question: "Arrange the sentences:\nP. The internet has transformed communication.\nQ. People can now connect instantly across the globe.\nR. However, it has also raised privacy concerns.\nS. Social media platforms are a major driver of this change.", optionA: "PQSR", optionB: "PSQR", optionC: "PQRS", optionD: "QPSR", correctAnswer: "B", explanation: "Topic (P) → explanation (S) → result (Q) → counterpoint (R). PSQR flows best.", difficulty: "MEDIUM", companies: ["TCS", "Infosys"] },
    { question: "Arrange the sentences:\nP. Exercise is essential for good health.\nQ. A balanced diet alone is not sufficient.\nR. Both diet and exercise must go hand in hand.\nS. Regular physical activity prevents many diseases.", optionA: "PQSR", optionB: "PSQR", optionC: "QPSR", optionD: "PSGR", correctAnswer: "B", explanation: "Statement (P) → supporting detail (S) → contrast (Q) → conclusion (R). PSQR.", difficulty: "EASY", companies: ["Wipro", "Cognizant"] },
    { question: "Arrange the sentences:\nP. Trees are vital for the environment.\nQ. They absorb carbon dioxide and release oxygen.\nR. Deforestation is therefore a major global concern.\nS. They also prevent soil erosion and support wildlife.", optionA: "PQSR", optionB: "PQRS", optionC: "QPSR", optionD: "PRSQ", correctAnswer: "A", explanation: "Topic (P) → function 1 (Q) → function 2 (S) → consequence (R). PQSR.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
    { question: "Arrange the sentences:\nP. He started with a small shop in his village.\nQ. Today he owns a chain of supermarkets.\nR. His story is an inspiration to many young entrepreneurs.\nS. Through hard work and determination, he expanded his business.", optionA: "PSQR", optionB: "PQSR", optionC: "SPQR", optionD: "QPSR", correctAnswer: "A", explanation: "Beginning (P) → process (S) → result (Q) → reflection (R). PSQR.", difficulty: "MEDIUM", companies: ["Infosys", "Cognizant"] },
    { question: "Arrange the sentences:\nP. Water scarcity is a growing problem worldwide.\nQ. Many regions face severe droughts every year.\nR. Rainwater harvesting can be an effective solution.\nS. Conservation efforts must be prioritized by governments.", optionA: "PQRS", optionB: "PQSR", optionC: "QPRS", optionD: "QPSR", correctAnswer: "B", explanation: "Problem (P) → evidence (Q) → government action (S) → solution (R). PQSR.", difficulty: "MEDIUM", companies: ["TCS", "Wipro"] },
    { question: "Arrange the sentences:\nP. Artificial intelligence is reshaping industries.\nQ. Healthcare and finance are among the most impacted sectors.\nR. Ethical concerns about AI are also growing.\nS. Automation has improved efficiency but displaced some workers.", optionA: "PQSR", optionB: "PSQR", optionC: "PQRS", optionD: "QPSR", correctAnswer: "A", explanation: "Topic (P) → examples (Q) → impact detail (S) → concern (R). PQSR.", difficulty: "MEDIUM", companies: ["Amazon", "Google"] },
    { question: "Arrange the sentences:\nP. Education is the foundation of a strong society.\nQ. It empowers individuals to make informed decisions.\nR. Countries that invest in education tend to prosper.\nS. Yet millions of children worldwide lack access to basic schooling.", optionA: "PQRS", optionB: "PRQS", optionC: "PQSR", optionD: "RQPS", correctAnswer: "A", explanation: "Foundation statement (P) → why (Q) → evidence (R) → contrast (S). PQRS.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
  ],

  // ── Reading Comprehension (id=82) ──
  82: [
    { question: "Read the passage: 'The Amazon rainforest produces about 20% of the world's oxygen. It is home to millions of species of plants and animals. Deforestation threatens this vital ecosystem.' What percentage of oxygen does the Amazon produce?", optionA: "10%", optionB: "15%", optionC: "20%", optionD: "25%", correctAnswer: "C", explanation: "The passage directly states 'about 20% of the world's oxygen'.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "Read: 'The invention of the printing press by Gutenberg in the 15th century revolutionized the spread of knowledge. Books became affordable and literacy rates soared across Europe.' What was the main effect of the printing press?", optionA: "Paper became expensive", optionB: "Knowledge spread more widely", optionC: "People stopped reading", optionD: "Only scholars could read", correctAnswer: "B", explanation: "The passage says it 'revolutionized the spread of knowledge' and books became affordable.", difficulty: "EASY", companies: ["TCS", "Wipro"] },
    { question: "Read: 'Solar energy is renewable and environmentally friendly. Unlike fossil fuels, it does not produce greenhouse gases. However, the initial cost of solar panel installation can be high.' What is a disadvantage of solar energy mentioned?", optionA: "It produces greenhouse gases", optionB: "It is not renewable", optionC: "High initial installation cost", optionD: "It is unreliable", correctAnswer: "C", explanation: "The passage mentions 'the initial cost of solar panel installation can be high' as a drawback.", difficulty: "EASY", companies: ["Accenture", "Cognizant"] },
    { question: "Read: 'Mahatma Gandhi led India's independence movement through nonviolent civil disobedience. His philosophy of Ahimsa inspired civil rights movements worldwide. He is often called the Father of the Nation.' What is Ahimsa?", optionA: "Armed resistance", optionB: "Nonviolence", optionC: "Political protest", optionD: "Economic boycott", correctAnswer: "B", explanation: "The passage connects Ahimsa with 'nonviolent civil disobedience', indicating it means nonviolence.", difficulty: "EASY", companies: ["TCS", "Infosys"] },
    { question: "Read: 'The human brain contains approximately 86 billion neurons. These neurons communicate through electrical and chemical signals. Damage to neurons can lead to neurological disorders such as Alzheimer's disease.' How do neurons communicate?", optionA: "Through blood flow", optionB: "Through electrical and chemical signals", optionC: "Through hormones only", optionD: "Through physical contact", correctAnswer: "B", explanation: "The passage states neurons 'communicate through electrical and chemical signals'.", difficulty: "EASY", companies: ["Wipro", "Cognizant"] },
    { question: "Read: 'Global warming is primarily caused by the burning of fossil fuels, which releases carbon dioxide into the atmosphere. This leads to a greenhouse effect, trapping heat and raising global temperatures. The Paris Agreement aims to limit warming to 1.5°C.' What does the Paris Agreement aim to do?", optionA: "Ban fossil fuels", optionB: "Plant more trees", optionC: "Limit warming to 1.5°C", optionD: "Reduce population", correctAnswer: "C", explanation: "The passage states 'The Paris Agreement aims to limit warming to 1.5°C'.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
    { question: "Read: 'Plastic pollution in oceans has reached alarming levels. Marine animals often mistake plastic for food, leading to ingestion and entanglement. Scientists estimate that by 2050, there could be more plastic than fish in the oceans.' By when could plastic outnumber fish?", optionA: "2030", optionB: "2040", optionC: "2050", optionD: "2060", correctAnswer: "C", explanation: "The passage states 'by 2050, there could be more plastic than fish'.", difficulty: "EASY", companies: ["Infosys", "Cognizant"] },
    { question: "Read: 'Shakespeare wrote 37 plays and 154 sonnets during his lifetime. His works explore themes of love, power, jealousy, and betrayal. He is widely regarded as the greatest writer in the English language.' How many sonnets did Shakespeare write?", optionA: "37", optionB: "100", optionC: "154", optionD: "200", correctAnswer: "C", explanation: "The passage states '154 sonnets'.", difficulty: "EASY", companies: ["TCS", "Wipro"] },
    { question: "Read: 'The Great Wall of China stretches over 13,000 miles. It was built over many centuries to protect against invasions from the north. Today it is a UNESCO World Heritage Site and a popular tourist destination.' Why was the Great Wall built?", optionA: "For trade routes", optionB: "To protect against northern invasions", optionC: "As a tourist attraction", optionD: "For water management", correctAnswer: "B", explanation: "The passage states it was built 'to protect against invasions from the north'.", difficulty: "EASY", companies: ["Accenture", "Cognizant"] },
    { question: "Read: 'Meditation has been shown to reduce stress and improve mental clarity. Regular practice can lower blood pressure and enhance emotional well-being. Many companies now offer meditation programs to their employees.' What benefit of meditation is NOT mentioned?", optionA: "Reduces stress", optionB: "Improves mental clarity", optionC: "Increases physical strength", optionD: "Lowers blood pressure", correctAnswer: "C", explanation: "Reduces stress, mental clarity, and lower blood pressure are all mentioned. Increasing physical strength is not.", difficulty: "MEDIUM", companies: ["TCS", "Infosys"] },
    { question: "Read: 'The Industrial Revolution began in Britain in the late 18th century. It marked a shift from agricultural economies to industrial manufacturing. Steam power and mechanized factories transformed production methods.' Where did the Industrial Revolution begin?", optionA: "France", optionB: "Germany", optionC: "Britain", optionD: "United States", correctAnswer: "C", explanation: "The passage states 'began in Britain'.", difficulty: "EASY", companies: ["Wipro", "Cognizant"] },
    { question: "Read: 'Vaccination is one of the most effective ways to prevent infectious diseases. Vaccines work by stimulating the immune system to produce antibodies. Herd immunity is achieved when a large percentage of the population is vaccinated.' What is herd immunity?", optionA: "When one person is vaccinated", optionB: "When animals are vaccinated", optionC: "When a large percentage of the population is vaccinated", optionD: "When vaccines are mandatory", correctAnswer: "C", explanation: "The passage defines herd immunity as being 'achieved when a large percentage of the population is vaccinated'.", difficulty: "EASY", companies: ["TCS", "Accenture"] },
    { question: "Read: 'Mount Everest, at 8,849 meters, is the tallest mountain above sea level. It is located in the Himalayas on the border of Nepal and Tibet. Hundreds of climbers attempt to summit it each year, though the journey is dangerous.' How tall is Mount Everest?", optionA: "8,000 meters", optionB: "8,611 meters", optionC: "8,849 meters", optionD: "9,000 meters", correctAnswer: "C", explanation: "The passage states 'at 8,849 meters'.", difficulty: "EASY", companies: ["Infosys", "Cognizant"] },
    { question: "Read: 'Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that was still edible. Its low moisture content and acidic pH create an inhospitable environment for bacteria.' Why doesn't honey spoil?", optionA: "It contains preservatives", optionB: "It is frozen", optionC: "Low moisture and acidic pH prevent bacterial growth", optionD: "It is sealed in airtight containers", correctAnswer: "C", explanation: "The passage explains 'low moisture content and acidic pH create an inhospitable environment for bacteria'.", difficulty: "MEDIUM", companies: ["TCS", "Wipro"] },
    { question: "Read: 'Electric vehicles (EVs) are becoming increasingly popular as concerns about climate change grow. EVs produce zero tailpipe emissions, reducing air pollution in cities. However, the environmental impact of battery production and disposal remains a challenge.' What challenge do EVs face?", optionA: "High fuel costs", optionB: "Noise pollution", optionC: "Battery production and disposal impact", optionD: "Slow speeds", correctAnswer: "C", explanation: "The passage mentions 'the environmental impact of battery production and disposal remains a challenge'.", difficulty: "MEDIUM", companies: ["Amazon", "Google"] },
  ],
};

async function main() {
  console.log("Seeding Verbal Ability topics...\n");

  const TOPIC_MAP: Record<number, string> = {
    81: "Fill in the Blanks",
    84: "Direct and Indirect Speech",
    76: "One Word Substitution",
    74: "Paragraph Formation",
    82: "Reading Comprehension",
  };

  for (const [topicIdStr, questions] of Object.entries(TOPICS)) {
    const topicId = Number(topicIdStr);
    const name = TOPIC_MAP[topicId] ?? `Topic ${topicId}`;

    const existing = await prisma.aptitudeQuestion.count({ where: { topicId } });
    if (existing >= 15) {
      console.log(`Skipping "${name}" (id=${topicId}) — already has ${existing} questions`);
      continue;
    }

    await prisma.aptitudeQuestion.createMany({
      data: questions.map((q) => ({ topicId, ...q })),
    });
    console.log(`Added ${questions.length} questions to "${name}" (id=${topicId})`);
  }

  await prisma.$disconnect();
  console.log("\nDone!");
}

main().catch((e) => { console.error(e); process.exit(1); });
